# generated by datamodel-codegen:
#   filename:  FuzzyFileSearchSessionStartParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel


class FuzzyFileSearchSessionStartParams(BaseModel):
    roots: list[str]
    sessionId: str
