# generated by datamodel-codegen:
#   filename:  PermissionsRequestApprovalParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AdditionalFileSystemPermissions(BaseModel):
    read: list[AbsolutePathBuf] | None = None
    write: list[AbsolutePathBuf] | None = None


class AdditionalNetworkPermissions(BaseModel):
    enabled: bool | None = None


class RequestPermissionProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class PermissionsRequestApprovalParams(BaseModel):
    itemId: str
    permissions: RequestPermissionProfile
    reason: str | None = None
    threadId: str
    turnId: str
