# generated by datamodel-codegen:
#   filename:  RequestId.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import Field, RootModel


class RequestId(RootModel[str | int]):
    root: str | int = Field(..., title='RequestId')
