# generated by datamodel-codegen:
#   filename:  CommandExecutionRequestApprovalParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AdditionalFileSystemPermissions(BaseModel):
    read: list[AbsolutePathBuf] | None = None
    write: list[AbsolutePathBuf] | None = None


class AdditionalNetworkPermissions(BaseModel):
    enabled: bool | None = None


class AdditionalPermissionProfile(BaseModel):
    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None


class Type(Enum):
    read = 'read'


class CommandAction1(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type58(Enum):
    listFiles = 'listFiles'


class CommandAction2(BaseModel):
    command: str
    path: str | None = None
    type: Type58 = Field(..., title='ListFilesCommandActionType')


class Type59(Enum):
    search = 'search'


class CommandAction3(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type59 = Field(..., title='SearchCommandActionType')


class Type60(Enum):
    unknown = 'unknown'


class CommandAction4(BaseModel):
    command: str
    type: Type60 = Field(..., title='UnknownCommandActionType')


class CommandAction(
    RootModel[CommandAction1 | CommandAction2 | CommandAction3 | CommandAction4]
):
    root: CommandAction1 | CommandAction2 | CommandAction3 | CommandAction4


class CommandExecutionApprovalDecision1(Enum):
    accept = 'accept'


class CommandExecutionApprovalDecision2(Enum):
    acceptForSession = 'acceptForSession'


class AcceptWithExecpolicyAmendment(BaseModel):
    execpolicy_amendment: list[str]


class CommandExecutionApprovalDecision3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendment


class CommandExecutionApprovalDecision5(Enum):
    decline = 'decline'


class CommandExecutionApprovalDecision6(Enum):
    cancel = 'cancel'


class NetworkApprovalProtocol(Enum):
    http = 'http'
    https = 'https'
    socks5Tcp = 'socks5Tcp'
    socks5Udp = 'socks5Udp'


class NetworkPolicyRuleAction(Enum):
    allow = 'allow'
    deny = 'deny'


class NetworkApprovalContext(BaseModel):
    host: str
    protocol: NetworkApprovalProtocol


class NetworkPolicyAmendment(BaseModel):
    action: NetworkPolicyRuleAction
    host: str


class ApplyNetworkPolicyAmendment(BaseModel):
    network_policy_amendment: NetworkPolicyAmendment


class CommandExecutionApprovalDecision4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendment


class CommandExecutionApprovalDecision(
    RootModel[
        CommandExecutionApprovalDecision1
        | CommandExecutionApprovalDecision2
        | CommandExecutionApprovalDecision3
        | CommandExecutionApprovalDecision4
        | CommandExecutionApprovalDecision5
        | CommandExecutionApprovalDecision6
    ]
):
    root: (
        CommandExecutionApprovalDecision1
        | CommandExecutionApprovalDecision2
        | CommandExecutionApprovalDecision3
        | CommandExecutionApprovalDecision4
        | CommandExecutionApprovalDecision5
        | CommandExecutionApprovalDecision6
    )


class CommandExecutionRequestApprovalParams(BaseModel):
    additionalPermissions: AdditionalPermissionProfile | None = Field(
        None, description='Optional additional permissions requested for this command.'
    )
    approvalId: str | None = Field(
        None,
        description='Unique identifier for this specific approval callback.\n\nFor regular shell/unified_exec approvals, this is null.\n\nFor zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used to disambiguate routing.',
    )
    availableDecisions: list[CommandExecutionApprovalDecision] | None = Field(
        None,
        description='Ordered list of decisions the client may present for this prompt.',
    )
    command: str | None = Field(None, description='The command to be executed.')
    commandActions: list[CommandAction] | None = Field(
        None, description='Best-effort parsed command actions for friendly display.'
    )
    cwd: AbsolutePathBuf | None = Field(
        None, description="The command's working directory."
    )
    itemId: str
    networkApprovalContext: NetworkApprovalContext | None = Field(
        None, description='Optional context for a managed-network approval prompt.'
    )
    proposedExecpolicyAmendment: list[str] | None = Field(
        None,
        description='Optional proposed execpolicy amendment to allow similar commands without prompting.',
    )
    proposedNetworkPolicyAmendments: list[NetworkPolicyAmendment] | None = Field(
        None,
        description='Optional proposed network policy amendments (allow/deny host) for future requests.',
    )
    reason: str | None = Field(
        None,
        description='Optional explanatory reason (e.g. request for network access).',
    )
    threadId: str
    turnId: str
