# generated by datamodel-codegen:
#   filename:  DynamicToolCallParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class DynamicToolCallParams(BaseModel):
    arguments: Any
    callId: str
    threadId: str
    tool: str
    turnId: str
