# generated by datamodel-codegen:
#   filename:  DynamicToolCallResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Type(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem1(BaseModel):
    text: str
    type: Type = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type76(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem2(BaseModel):
    imageUrl: str
    type: Type76 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem(
    RootModel[DynamicToolCallOutputContentItem1 | DynamicToolCallOutputContentItem2]
):
    root: DynamicToolCallOutputContentItem1 | DynamicToolCallOutputContentItem2


class DynamicToolCallResponse(BaseModel):
    contentItems: list[DynamicToolCallOutputContentItem]
    success: bool
