# generated by datamodel-codegen:
#   filename:  FuzzyFileSearchSessionStopResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel


class FuzzyFileSearchSessionStopResponse(BaseModel):
    pass
