# generated by datamodel-codegen:
#   filename:  JSONRPCError.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class JSONRPCErrorError(BaseModel):
    code: int
    data: Any | None = None
    message: str


class RequestId(RootModel[str | int]):
    root: str | int


class JSONRPCError(BaseModel):
    error: JSONRPCErrorError
    id: RequestId
