# generated by datamodel-codegen:
#   filename:  v2/AccountRateLimitsUpdatedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class CreditsSnapshot(BaseModel):
    balance: str | None = None
    hasCredits: bool
    unlimited: bool


class PlanType(Enum):
    free = 'free'
    go = 'go'
    plus = 'plus'
    pro = 'pro'
    prolite = 'prolite'
    team = 'team'
    self_serve_business_usage_based = 'self_serve_business_usage_based'
    business = 'business'
    enterprise_cbp_usage_based = 'enterprise_cbp_usage_based'
    enterprise = 'enterprise'
    edu = 'edu'
    unknown = 'unknown'


class RateLimitWindow(BaseModel):
    resetsAt: int | None = None
    usedPercent: int
    windowDurationMins: int | None = None


class RateLimitSnapshot(BaseModel):
    credits: CreditsSnapshot | None = None
    limitId: str | None = None
    limitName: str | None = None
    planType: PlanType | None = None
    primary: RateLimitWindow | None = None
    secondary: RateLimitWindow | None = None


class AccountRateLimitsUpdatedNotification(BaseModel):
    rateLimits: RateLimitSnapshot
