# generated by datamodel-codegen:
#   filename:  v2/CollaborationModeListResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class ModeKind(Enum):
    plan = 'plan'
    default = 'default'


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class CollaborationModeMask(BaseModel):
    mode: ModeKind | None = None
    model: str | None = None
    name: str
    reasoning_effort: ReasoningEffort | None = None


class CollaborationModeListResponse(BaseModel):
    data: list[CollaborationModeMask]
