# generated by datamodel-codegen:
#   filename:  v2/CommandExecTerminateParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CommandExecTerminateParams(BaseModel):
    processId: str = Field(
        ...,
        description='Client-supplied, connection-scoped `processId` from the original `command/exec` request.',
    )
