# generated by datamodel-codegen:
#   filename:  v2/CommandExecParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class CommandExecTerminalSize(BaseModel):
    cols: conint(ge=0) = Field(..., description='Terminal width in character cells.')
    rows: conint(ge=0) = Field(..., description='Terminal height in character cells.')


class NetworkAccess(Enum):
    restricted = 'restricted'
    enabled = 'enabled'


class Type(Enum):
    restricted = 'restricted'


class ReadOnlyAccess(BaseModel):
    includePlatformDefaults: bool | None = True
    readableRoots: list[AbsolutePathBuf] | None = Field([], validate_default=True)
    type: Type = Field(..., title='RestrictedReadOnlyAccessType')


class Type52(Enum):
    fullAccess = 'fullAccess'


class ReadOnlyAccess5(BaseModel):
    type: Type52 = Field(..., title='FullAccessReadOnlyAccessType')


class ReadOnlyAccess3(RootModel[ReadOnlyAccess | ReadOnlyAccess5]):
    root: ReadOnlyAccess | ReadOnlyAccess5


class Type53(Enum):
    dangerFullAccess = 'dangerFullAccess'


class SandboxPolicy5(BaseModel):
    type: Type53 = Field(..., title='DangerFullAccessSandboxPolicyType')


class Type54(Enum):
    readOnly = 'readOnly'


class SandboxPolicy6(BaseModel):
    access: ReadOnlyAccess3 | None = Field(
        {'type': 'fullAccess'}, validate_default=True
    )
    networkAccess: bool | None = False
    type: Type54 = Field(..., title='ReadOnlySandboxPolicyType')


class Type55(Enum):
    externalSandbox = 'externalSandbox'


class SandboxPolicy7(BaseModel):
    networkAccess: NetworkAccess | None = 'restricted'
    type: Type55 = Field(..., title='ExternalSandboxSandboxPolicyType')


class Type56(Enum):
    workspaceWrite = 'workspaceWrite'


class SandboxPolicy8(BaseModel):
    excludeSlashTmp: bool | None = False
    excludeTmpdirEnvVar: bool | None = False
    networkAccess: bool | None = False
    readOnlyAccess: ReadOnlyAccess3 | None = Field(
        {'type': 'fullAccess'}, validate_default=True
    )
    type: Type56 = Field(..., title='WorkspaceWriteSandboxPolicyType')
    writableRoots: list[AbsolutePathBuf] | None = Field([], validate_default=True)


class SandboxPolicy(
    RootModel[SandboxPolicy5 | SandboxPolicy6 | SandboxPolicy7 | SandboxPolicy8]
):
    root: SandboxPolicy5 | SandboxPolicy6 | SandboxPolicy7 | SandboxPolicy8


class CommandExecParams(BaseModel):
    command: list[str] = Field(
        ..., description='Command argv vector. Empty arrays are rejected.'
    )
    cwd: str | None = Field(
        None, description='Optional working directory. Defaults to the server cwd.'
    )
    disableOutputCap: bool | None = Field(
        None,
        description='Disable stdout/stderr capture truncation for this request.\n\nCannot be combined with `outputBytesCap`.',
    )
    disableTimeout: bool | None = Field(
        None,
        description='Disable the timeout entirely for this request.\n\nCannot be combined with `timeoutMs`.',
    )
    env: dict[str, Any] | None = Field(
        None,
        description='Optional environment overrides merged into the server-computed environment.\n\nMatching names override inherited values. Set a key to `null` to unset an inherited variable.',
    )
    outputBytesCap: conint(ge=0) | None = Field(
        None,
        description='Optional per-stream stdout/stderr capture cap in bytes.\n\nWhen omitted, the server default applies. Cannot be combined with `disableOutputCap`.',
    )
    processId: str | None = Field(
        None,
        description='Optional client-supplied, connection-scoped process id.\n\nRequired for `tty`, `streamStdin`, `streamStdoutStderr`, and follow-up `command/exec/write`, `command/exec/resize`, and `command/exec/terminate` calls. When omitted, buffered execution gets an internal id that is not exposed to the client.',
    )
    sandboxPolicy: SandboxPolicy | None = Field(
        None,
        description="Optional sandbox policy for this command.\n\nUses the same shape as thread/turn execution sandbox configuration and defaults to the user's configured policy when omitted.",
    )
    size: CommandExecTerminalSize | None = Field(
        None,
        description='Optional initial PTY size in character cells. Only valid when `tty` is true.',
    )
    streamStdin: bool | None = Field(
        None,
        description='Allow follow-up `command/exec/write` requests to write stdin bytes.\n\nRequires a client-supplied `processId`.',
    )
    streamStdoutStderr: bool | None = Field(
        None,
        description='Stream stdout/stderr via `command/exec/outputDelta` notifications.\n\nStreamed bytes are not duplicated into the final response and require a client-supplied `processId`.',
    )
    timeoutMs: int | None = Field(
        None,
        description='Optional timeout in milliseconds.\n\nWhen omitted, the server default applies. Cannot be combined with `disableTimeout`.',
    )
    tty: bool | None = Field(
        None,
        description='Enable PTY mode.\n\nThis implies `streamStdin` and `streamStdoutStderr`.',
    )
