# generated by datamodel-codegen:
#   filename:  v2/ItemGuardianApprovalReviewStartedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class Type(Enum):
    command = 'command'


class Type123(Enum):
    execve = 'execve'


class Type124(Enum):
    applyPatch = 'applyPatch'


class GuardianApprovalReviewAction8(BaseModel):
    cwd: AbsolutePathBuf
    files: list[AbsolutePathBuf]
    type: Type124 = Field(..., title='ApplyPatchGuardianApprovalReviewActionType')


class Type125(Enum):
    networkAccess = 'networkAccess'


class Type126(Enum):
    mcpToolCall = 'mcpToolCall'


class GuardianApprovalReviewAction10(BaseModel):
    connectorId: str | None = None
    connectorName: str | None = None
    server: str
    toolName: str
    toolTitle: str | None = None
    type: Type126 = Field(..., title='McpToolCallGuardianApprovalReviewActionType')


class GuardianApprovalReviewStatus(Enum):
    inProgress = 'inProgress'
    approved = 'approved'
    denied = 'denied'
    timedOut = 'timedOut'
    aborted = 'aborted'


class GuardianCommandSource(Enum):
    shell = 'shell'
    unifiedExec = 'unifiedExec'


class GuardianRiskLevel(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class GuardianUserAuthorization(Enum):
    unknown = 'unknown'
    low = 'low'
    medium = 'medium'
    high = 'high'


class NetworkApprovalProtocol(Enum):
    http = 'http'
    https = 'https'
    socks5Tcp = 'socks5Tcp'
    socks5Udp = 'socks5Udp'


class GuardianApprovalReview(BaseModel):
    rationale: str | None = None
    riskLevel: GuardianRiskLevel | None = None
    status: GuardianApprovalReviewStatus
    userAuthorization: GuardianUserAuthorization | None = None


class GuardianApprovalReviewAction6(BaseModel):
    command: str
    cwd: AbsolutePathBuf
    source: GuardianCommandSource
    type: Type = Field(..., title='CommandGuardianApprovalReviewActionType')


class GuardianApprovalReviewAction7(BaseModel):
    argv: list[str]
    cwd: AbsolutePathBuf
    program: str
    source: GuardianCommandSource
    type: Type123 = Field(..., title='ExecveGuardianApprovalReviewActionType')


class GuardianApprovalReviewAction9(BaseModel):
    host: str
    port: conint(ge=0)
    protocol: NetworkApprovalProtocol
    target: str
    type: Type125 = Field(..., title='NetworkAccessGuardianApprovalReviewActionType')


class GuardianApprovalReviewAction(
    RootModel[
        GuardianApprovalReviewAction6
        | GuardianApprovalReviewAction7
        | GuardianApprovalReviewAction8
        | GuardianApprovalReviewAction9
        | GuardianApprovalReviewAction10
    ]
):
    root: (
        GuardianApprovalReviewAction6
        | GuardianApprovalReviewAction7
        | GuardianApprovalReviewAction8
        | GuardianApprovalReviewAction9
        | GuardianApprovalReviewAction10
    )


class ItemGuardianApprovalReviewStartedNotification(BaseModel):
    action: GuardianApprovalReviewAction
    review: GuardianApprovalReview
    reviewId: str = Field(..., description='Stable identifier for this review.')
    targetItemId: str | None = Field(
        None,
        description='Identifier for the reviewed item or tool call when one exists.\n\nIn most cases, one review maps to one target item. The exceptions are - execve reviews, where a single command may contain multiple execve calls to review (only possible when using the shell_zsh_fork feature) - network policy reviews, where there is no target item\n\nA network call is triggered by a CommandExecution item, so having a target_item_id set to the CommandExecution item would be misleading because the review is about the network call, not the command execution. Therefore, target_item_id is set to None for network policy reviews.',
    )
    threadId: str
    turnId: str
