# generated by datamodel-codegen:
#   filename:  v2/ItemCompletedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type84(Enum):
    listFiles = 'listFiles'


class CommandAction7(BaseModel):
    command: str
    path: str | None = None
    type: Type84 = Field(..., title='ListFilesCommandActionType')


class Type85(Enum):
    search = 'search'


class CommandAction8(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type85 = Field(..., title='SearchCommandActionType')


class Type86(Enum):
    unknown = 'unknown'


class CommandAction9(BaseModel):
    command: str
    type: Type86 = Field(..., title='UnknownCommandActionType')


class CommandAction5(
    RootModel[CommandAction | CommandAction7 | CommandAction8 | CommandAction9]
):
    root: CommandAction | CommandAction7 | CommandAction8 | CommandAction9


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type87(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type87 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type88(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem5(BaseModel):
    imageUrl: str
    type: Type88 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem3(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem5]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem5


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class McpToolCallError(BaseModel):
    message: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase5(Enum):
    final_answer = 'final_answer'


class MessagePhase3(RootModel[MessagePhase | MessagePhase5]):
    root: MessagePhase | MessagePhase5 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type89(Enum):
    add = 'add'


class PatchChangeKind1(BaseModel):
    type: Type89 = Field(..., title='AddPatchChangeKindType')


class Type90(Enum):
    delete = 'delete'


class PatchChangeKind2(BaseModel):
    type: Type90 = Field(..., title='DeletePatchChangeKindType')


class Type91(Enum):
    update = 'update'


class PatchChangeKind3(BaseModel):
    move_path: str | None = None
    type: Type91 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind1 | PatchChangeKind2 | PatchChangeKind3]
):
    root: PatchChangeKind1 | PatchChangeKind2 | PatchChangeKind3


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class Type92(Enum):
    userMessage = 'userMessage'


class Type93(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem2(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type93 = Field(..., title='HookPromptThreadItemType')


class Type94(Enum):
    agentMessage = 'agentMessage'


class Type95(Enum):
    plan = 'plan'


class ThreadItem4(BaseModel):
    id: str
    text: str
    type: Type95 = Field(..., title='PlanThreadItemType')


class Type96(Enum):
    reasoning = 'reasoning'


class ThreadItem5(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type96 = Field(..., title='ReasoningThreadItemType')


class Type97(Enum):
    commandExecution = 'commandExecution'


class ThreadItem6(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction5] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type97 = Field(..., title='CommandExecutionThreadItemType')


class Type98(Enum):
    fileChange = 'fileChange'


class Type99(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem8(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type99 = Field(..., title='McpToolCallThreadItemType')


class Type100(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem9(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem3] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type100 = Field(..., title='DynamicToolCallThreadItemType')


class Type101(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type102(Enum):
    webSearch = 'webSearch'


class Type103(Enum):
    imageView = 'imageView'


class ThreadItem12(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type103 = Field(..., title='ImageViewThreadItemType')


class Type104(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem13(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type104 = Field(..., title='ImageGenerationThreadItemType')


class Type105(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem14(BaseModel):
    id: str
    review: str
    type: Type105 = Field(..., title='EnteredReviewModeThreadItemType')


class Type106(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem15(BaseModel):
    id: str
    review: str
    type: Type106 = Field(..., title='ExitedReviewModeThreadItemType')


class Type107(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem16(BaseModel):
    id: str
    type: Type107 = Field(..., title='ContextCompactionThreadItemType')


class Type108(Enum):
    text = 'text'


class UserInput6(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type108 = Field(..., title='TextUserInputType')


class Type109(Enum):
    image = 'image'


class UserInput7(BaseModel):
    type: Type109 = Field(..., title='ImageUserInputType')
    url: str


class Type110(Enum):
    localImage = 'localImage'


class UserInput8(BaseModel):
    path: str
    type: Type110 = Field(..., title='LocalImageUserInputType')


class Type111(Enum):
    skill = 'skill'


class UserInput9(BaseModel):
    name: str
    path: str
    type: Type111 = Field(..., title='SkillUserInputType')


class Type112(Enum):
    mention = 'mention'


class UserInput10(BaseModel):
    name: str
    path: str
    type: Type112 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput6 | UserInput7 | UserInput8 | UserInput9 | UserInput10]
):
    root: UserInput6 | UserInput7 | UserInput8 | UserInput9 | UserInput10


class Type113(Enum):
    search = 'search'


class WebSearchAction1(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type113 = Field(..., title='SearchWebSearchActionType')


class Type114(Enum):
    openPage = 'openPage'


class WebSearchAction2(BaseModel):
    type: Type114 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type115(Enum):
    findInPage = 'findInPage'


class WebSearchAction3(BaseModel):
    pattern: str | None = None
    type: Type115 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type116(Enum):
    other = 'other'


class WebSearchAction4(BaseModel):
    type: Type116 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[WebSearchAction1 | WebSearchAction2 | WebSearchAction3 | WebSearchAction4]
):
    root: WebSearchAction1 | WebSearchAction2 | WebSearchAction3 | WebSearchAction4


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class ThreadItem1(BaseModel):
    content: list[UserInput]
    id: str
    type: Type92 = Field(..., title='UserMessageThreadItemType')


class ThreadItem3(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase3 | None = None
    text: str
    type: Type94 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem7(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type98 = Field(..., title='FileChangeThreadItemType')


class ThreadItem10(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type101 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem11(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type102 = Field(..., title='WebSearchThreadItemType')


class ThreadItem(
    RootModel[
        ThreadItem1
        | ThreadItem2
        | ThreadItem3
        | ThreadItem4
        | ThreadItem5
        | ThreadItem6
        | ThreadItem7
        | ThreadItem8
        | ThreadItem9
        | ThreadItem10
        | ThreadItem11
        | ThreadItem12
        | ThreadItem13
        | ThreadItem14
        | ThreadItem15
        | ThreadItem16
    ]
):
    root: (
        ThreadItem1
        | ThreadItem2
        | ThreadItem3
        | ThreadItem4
        | ThreadItem5
        | ThreadItem6
        | ThreadItem7
        | ThreadItem8
        | ThreadItem9
        | ThreadItem10
        | ThreadItem11
        | ThreadItem12
        | ThreadItem13
        | ThreadItem14
        | ThreadItem15
        | ThreadItem16
    )


class ItemCompletedNotification(BaseModel):
    item: ThreadItem
    threadId: str
    turnId: str
