# generated by datamodel-codegen:
#   filename:  v2/McpServerToolCallParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class McpServerToolCallParams(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    arguments: Any | None = None
    server: str
    threadId: str
    tool: str
