# generated by datamodel-codegen:
#   filename:  v2/PluginUninstallParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PluginUninstallParams(BaseModel):
    forceRemoteSync: bool | None = Field(
        None,
        description='When true, apply the remote plugin change before the local uninstall flow.',
    )
    pluginId: str
