# generated by datamodel-codegen:
#   filename:  v2/RawResponseItemCompletedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class Type(Enum):
    input_text = 'input_text'


class ContentItem(BaseModel):
    text: str
    type: Type = Field(..., title='InputTextContentItemType')


class Type172(Enum):
    input_image = 'input_image'


class ContentItem6(BaseModel):
    image_url: str
    type: Type172 = Field(..., title='InputImageContentItemType')


class Type173(Enum):
    output_text = 'output_text'


class ContentItem7(BaseModel):
    text: str
    type: Type173 = Field(..., title='OutputTextContentItemType')


class ContentItem4(RootModel[ContentItem | ContentItem6 | ContentItem7]):
    root: ContentItem | ContentItem6 | ContentItem7


class Type174(Enum):
    input_text = 'input_text'


class FunctionCallOutputContentItem3(BaseModel):
    text: str
    type: Type174 = Field(..., title='InputTextFunctionCallOutputContentItemType')


class Type175(Enum):
    input_image = 'input_image'


class GhostCommit(BaseModel):
    id: str
    parent: str | None = None
    preexisting_untracked_dirs: list[str]
    preexisting_untracked_files: list[str]


class ImageDetail(Enum):
    auto = 'auto'
    low = 'low'
    high = 'high'
    original = 'original'


class Type176(Enum):
    exec = 'exec'


class LocalShellAction(BaseModel):
    command: list[str]
    env: dict[str, Any] | None = None
    timeout_ms: conint(ge=0) | None = None
    type: Type176 = Field(..., title='ExecLocalShellActionType')
    user: str | None = None
    working_directory: str | None = None


class LocalShellAction2(RootModel[LocalShellAction]):
    root: LocalShellAction


class LocalShellStatus(Enum):
    completed = 'completed'
    in_progress = 'in_progress'
    incomplete = 'incomplete'


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase11(Enum):
    final_answer = 'final_answer'


class MessagePhase9(RootModel[MessagePhase | MessagePhase11]):
    root: MessagePhase | MessagePhase11 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class Type177(Enum):
    reasoning_text = 'reasoning_text'


class ReasoningItemContent(BaseModel):
    text: str
    type: Type177 = Field(..., title='ReasoningTextReasoningItemContentType')


class Type178(Enum):
    text = 'text'


class ReasoningItemContent5(BaseModel):
    text: str
    type: Type178 = Field(..., title='TextReasoningItemContentType')


class ReasoningItemContent3(RootModel[ReasoningItemContent | ReasoningItemContent5]):
    root: ReasoningItemContent | ReasoningItemContent5


class Type179(Enum):
    summary_text = 'summary_text'


class ReasoningItemReasoningSummary(BaseModel):
    text: str
    type: Type179 = Field(..., title='SummaryTextReasoningItemReasoningSummaryType')


class ReasoningItemReasoningSummary2(RootModel[ReasoningItemReasoningSummary]):
    root: ReasoningItemReasoningSummary


class Type180(Enum):
    message = 'message'


class ResponseItem15(BaseModel):
    content: list[ContentItem4]
    end_turn: bool | None = None
    id: str | None = None
    phase: MessagePhase9 | None = None
    role: str
    type: Type180 = Field(..., title='MessageResponseItemType')


class Type181(Enum):
    reasoning = 'reasoning'


class ResponseItem16(BaseModel):
    content: list[ReasoningItemContent3] | None = None
    encrypted_content: str | None = None
    summary: list[ReasoningItemReasoningSummary2]
    type: Type181 = Field(..., title='ReasoningResponseItemType')


class Type182(Enum):
    local_shell_call = 'local_shell_call'


class ResponseItem17(BaseModel):
    action: LocalShellAction2
    call_id: str | None = Field(None, description='Set when using the Responses API.')
    id: str | None = Field(
        None,
        description='Legacy id field retained for compatibility with older payloads.',
    )
    status: LocalShellStatus
    type: Type182 = Field(..., title='LocalShellCallResponseItemType')


class Type183(Enum):
    function_call = 'function_call'


class ResponseItem18(BaseModel):
    arguments: str
    call_id: str
    id: str | None = None
    name: str
    namespace: str | None = None
    type: Type183 = Field(..., title='FunctionCallResponseItemType')


class Type184(Enum):
    tool_search_call = 'tool_search_call'


class ResponseItem19(BaseModel):
    arguments: Any
    call_id: str | None = None
    execution: str
    id: str | None = None
    status: str | None = None
    type: Type184 = Field(..., title='ToolSearchCallResponseItemType')


class Type185(Enum):
    function_call_output = 'function_call_output'


class Type186(Enum):
    custom_tool_call = 'custom_tool_call'


class ResponseItem21(BaseModel):
    call_id: str
    id: str | None = None
    input: str
    name: str
    status: str | None = None
    type: Type186 = Field(..., title='CustomToolCallResponseItemType')


class Type187(Enum):
    custom_tool_call_output = 'custom_tool_call_output'


class Type188(Enum):
    tool_search_output = 'tool_search_output'


class ResponseItem23(BaseModel):
    call_id: str | None = None
    execution: str
    status: str
    tools: list[Any]
    type: Type188 = Field(..., title='ToolSearchOutputResponseItemType')


class Type189(Enum):
    web_search_call = 'web_search_call'


class Type190(Enum):
    image_generation_call = 'image_generation_call'


class ResponseItem25(BaseModel):
    id: str
    result: str
    revised_prompt: str | None = None
    status: str
    type: Type190 = Field(..., title='ImageGenerationCallResponseItemType')


class Type191(Enum):
    ghost_snapshot = 'ghost_snapshot'


class ResponseItem26(BaseModel):
    ghost_commit: GhostCommit
    type: Type191 = Field(..., title='GhostSnapshotResponseItemType')


class Type192(Enum):
    compaction = 'compaction'


class ResponseItem27(BaseModel):
    encrypted_content: str
    type: Type192 = Field(..., title='CompactionResponseItemType')


class Type193(Enum):
    other = 'other'


class ResponseItem28(BaseModel):
    type: Type193 = Field(..., title='OtherResponseItemType')


class Type194(Enum):
    search = 'search'


class ResponsesApiWebSearchAction5(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type194 = Field(..., title='SearchResponsesApiWebSearchActionType')


class Type195(Enum):
    open_page = 'open_page'


class ResponsesApiWebSearchAction6(BaseModel):
    type: Type195 = Field(..., title='OpenPageResponsesApiWebSearchActionType')
    url: str | None = None


class Type196(Enum):
    find_in_page = 'find_in_page'


class ResponsesApiWebSearchAction7(BaseModel):
    pattern: str | None = None
    type: Type196 = Field(..., title='FindInPageResponsesApiWebSearchActionType')
    url: str | None = None


class Type197(Enum):
    other = 'other'


class ResponsesApiWebSearchAction8(BaseModel):
    type: Type197 = Field(..., title='OtherResponsesApiWebSearchActionType')


class ResponsesApiWebSearchAction(
    RootModel[
        ResponsesApiWebSearchAction5
        | ResponsesApiWebSearchAction6
        | ResponsesApiWebSearchAction7
        | ResponsesApiWebSearchAction8
    ]
):
    root: (
        ResponsesApiWebSearchAction5
        | ResponsesApiWebSearchAction6
        | ResponsesApiWebSearchAction7
        | ResponsesApiWebSearchAction8
    )


class FunctionCallOutputContentItem4(BaseModel):
    detail: ImageDetail | None = None
    image_url: str
    type: Type175 = Field(..., title='InputImageFunctionCallOutputContentItemType')


class FunctionCallOutputContentItem(
    RootModel[FunctionCallOutputContentItem3 | FunctionCallOutputContentItem4]
):
    root: FunctionCallOutputContentItem3 | FunctionCallOutputContentItem4 = Field(
        ...,
        description='Responses API compatible content items that can be returned by a tool call. This is a subset of ContentItem with the types we support as function call outputs.',
    )


class ResponseItem24(BaseModel):
    action: ResponsesApiWebSearchAction | None = None
    id: str | None = None
    status: str | None = None
    type: Type189 = Field(..., title='WebSearchCallResponseItemType')


class FunctionCallOutputBody(RootModel[str | list[FunctionCallOutputContentItem]]):
    root: str | list[FunctionCallOutputContentItem]


class ResponseItem20(BaseModel):
    call_id: str
    output: FunctionCallOutputBody
    type: Type185 = Field(..., title='FunctionCallOutputResponseItemType')


class ResponseItem22(BaseModel):
    call_id: str
    name: str | None = None
    output: FunctionCallOutputBody
    type: Type187 = Field(..., title='CustomToolCallOutputResponseItemType')


class ResponseItem(
    RootModel[
        ResponseItem15
        | ResponseItem16
        | ResponseItem17
        | ResponseItem18
        | ResponseItem19
        | ResponseItem20
        | ResponseItem21
        | ResponseItem22
        | ResponseItem23
        | ResponseItem24
        | ResponseItem25
        | ResponseItem26
        | ResponseItem27
        | ResponseItem28
    ]
):
    root: (
        ResponseItem15
        | ResponseItem16
        | ResponseItem17
        | ResponseItem18
        | ResponseItem19
        | ResponseItem20
        | ResponseItem21
        | ResponseItem22
        | ResponseItem23
        | ResponseItem24
        | ResponseItem25
        | ResponseItem26
        | ResponseItem27
        | ResponseItem28
    )


class RawResponseItemCompletedNotification(BaseModel):
    item: ResponseItem
    threadId: str
    turnId: str
