# generated by datamodel-codegen:
#   filename:  v2/TerminalInteractionNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel


class TerminalInteractionNotification(BaseModel):
    itemId: str
    processId: str
    stdin: str
    threadId: str
    turnId: str
