# generated by datamodel-codegen:
#   filename:  v2/ThreadListResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AgentPath(RootModel[str]):
    root: str


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CodexErrorInfo(Enum):
    contextWindowExceeded = 'contextWindowExceeded'
    usageLimitExceeded = 'usageLimitExceeded'
    serverOverloaded = 'serverOverloaded'
    internalServerError = 'internalServerError'
    unauthorized = 'unauthorized'
    badRequest = 'badRequest'
    threadRollbackFailed = 'threadRollbackFailed'
    sandboxError = 'sandboxError'
    other = 'other'


class HttpConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo30(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo31(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo32(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo33(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type335(Enum):
    listFiles = 'listFiles'


class CommandAction37(BaseModel):
    command: str
    path: str | None = None
    type: Type335 = Field(..., title='ListFilesCommandActionType')


class Type336(Enum):
    search = 'search'


class CommandAction38(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type336 = Field(..., title='SearchCommandActionType')


class Type337(Enum):
    unknown = 'unknown'


class CommandAction39(BaseModel):
    command: str
    type: Type337 = Field(..., title='UnknownCommandActionType')


class CommandAction35(
    RootModel[CommandAction | CommandAction37 | CommandAction38 | CommandAction39]
):
    root: CommandAction | CommandAction37 | CommandAction38 | CommandAction39


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type338(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type338 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type339(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem20(BaseModel):
    imageUrl: str
    type: Type339 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem18(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem20]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem20


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class GitInfo(BaseModel):
    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class McpToolCallError(BaseModel):
    message: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase23(Enum):
    final_answer = 'final_answer'


class MessagePhase21(RootModel[MessagePhase | MessagePhase23]):
    root: MessagePhase | MessagePhase23 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class NonSteerableTurnKind(Enum):
    review = 'review'
    compact = 'compact'


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type340(Enum):
    add = 'add'


class PatchChangeKind16(BaseModel):
    type: Type340 = Field(..., title='AddPatchChangeKindType')


class Type341(Enum):
    delete = 'delete'


class PatchChangeKind17(BaseModel):
    type: Type341 = Field(..., title='DeletePatchChangeKindType')


class Type342(Enum):
    update = 'update'


class PatchChangeKind18(BaseModel):
    move_path: str | None = None
    type: Type342 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind16 | PatchChangeKind17 | PatchChangeKind18]
):
    root: PatchChangeKind16 | PatchChangeKind17 | PatchChangeKind18


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class SessionSource(Enum):
    cli = 'cli'
    vscode = 'vscode'
    exec = 'exec'
    appServer = 'appServer'
    unknown = 'unknown'


class SessionSource10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom: str


class SubAgentSource7(Enum):
    review = 'review'
    compact = 'compact'
    memory_consolidation = 'memory_consolidation'


class SubAgentSource9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    other: str


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class ThreadActiveFlag(Enum):
    waitingOnApproval = 'waitingOnApproval'
    waitingOnUserInput = 'waitingOnUserInput'


class ThreadId(RootModel[str]):
    root: str


class Type343(Enum):
    userMessage = 'userMessage'


class Type344(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type344 = Field(..., title='HookPromptThreadItemType')


class Type345(Enum):
    agentMessage = 'agentMessage'


class Type346(Enum):
    plan = 'plan'


class ThreadItem87(BaseModel):
    id: str
    text: str
    type: Type346 = Field(..., title='PlanThreadItemType')


class Type347(Enum):
    reasoning = 'reasoning'


class ThreadItem88(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type347 = Field(..., title='ReasoningThreadItemType')


class Type348(Enum):
    commandExecution = 'commandExecution'


class ThreadItem89(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction35] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type348 = Field(..., title='CommandExecutionThreadItemType')


class Type349(Enum):
    fileChange = 'fileChange'


class Type350(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem91(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type350 = Field(..., title='McpToolCallThreadItemType')


class Type351(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem92(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem18] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type351 = Field(..., title='DynamicToolCallThreadItemType')


class Type352(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type353(Enum):
    webSearch = 'webSearch'


class Type354(Enum):
    imageView = 'imageView'


class ThreadItem95(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type354 = Field(..., title='ImageViewThreadItemType')


class Type355(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem96(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type355 = Field(..., title='ImageGenerationThreadItemType')


class Type356(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem97(BaseModel):
    id: str
    review: str
    type: Type356 = Field(..., title='EnteredReviewModeThreadItemType')


class Type357(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem98(BaseModel):
    id: str
    review: str
    type: Type357 = Field(..., title='ExitedReviewModeThreadItemType')


class Type358(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem99(BaseModel):
    id: str
    type: Type358 = Field(..., title='ContextCompactionThreadItemType')


class Type359(Enum):
    notLoaded = 'notLoaded'


class ThreadStatus9(BaseModel):
    type: Type359 = Field(..., title='NotLoadedThreadStatusType')


class Type360(Enum):
    idle = 'idle'


class ThreadStatus10(BaseModel):
    type: Type360 = Field(..., title='IdleThreadStatusType')


class Type361(Enum):
    systemError = 'systemError'


class ThreadStatus11(BaseModel):
    type: Type361 = Field(..., title='SystemErrorThreadStatusType')


class Type362(Enum):
    active = 'active'


class ThreadStatus12(BaseModel):
    activeFlags: list[ThreadActiveFlag]
    type: Type362 = Field(..., title='ActiveThreadStatusType')


class ThreadStatus(
    RootModel[ThreadStatus9 | ThreadStatus10 | ThreadStatus11 | ThreadStatus12]
):
    root: ThreadStatus9 | ThreadStatus10 | ThreadStatus11 | ThreadStatus12


class TurnStatus(Enum):
    completed = 'completed'
    interrupted = 'interrupted'
    failed = 'failed'
    inProgress = 'inProgress'


class Type363(Enum):
    text = 'text'


class UserInput31(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type363 = Field(..., title='TextUserInputType')


class Type364(Enum):
    image = 'image'


class UserInput32(BaseModel):
    type: Type364 = Field(..., title='ImageUserInputType')
    url: str


class Type365(Enum):
    localImage = 'localImage'


class UserInput33(BaseModel):
    path: str
    type: Type365 = Field(..., title='LocalImageUserInputType')


class Type366(Enum):
    skill = 'skill'


class UserInput34(BaseModel):
    name: str
    path: str
    type: Type366 = Field(..., title='SkillUserInputType')


class Type367(Enum):
    mention = 'mention'


class UserInput35(BaseModel):
    name: str
    path: str
    type: Type367 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput31 | UserInput32 | UserInput33 | UserInput34 | UserInput35]
):
    root: UserInput31 | UserInput32 | UserInput33 | UserInput34 | UserInput35


class Type368(Enum):
    search = 'search'


class WebSearchAction21(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type368 = Field(..., title='SearchWebSearchActionType')


class Type369(Enum):
    openPage = 'openPage'


class WebSearchAction22(BaseModel):
    type: Type369 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type370(Enum):
    findInPage = 'findInPage'


class WebSearchAction23(BaseModel):
    pattern: str | None = None
    type: Type370 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type371(Enum):
    other = 'other'


class WebSearchAction24(BaseModel):
    type: Type371 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[
        WebSearchAction21 | WebSearchAction22 | WebSearchAction23 | WebSearchAction24
    ]
):
    root: WebSearchAction21 | WebSearchAction22 | WebSearchAction23 | WebSearchAction24


class ActiveTurnNotSteerable(BaseModel):
    turnKind: NonSteerableTurnKind


class CodexErrorInfo34(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CodexErrorInfo28(
    RootModel[
        CodexErrorInfo
        | CodexErrorInfo30
        | CodexErrorInfo31
        | CodexErrorInfo32
        | CodexErrorInfo33
        | CodexErrorInfo34
    ]
):
    root: (
        CodexErrorInfo
        | CodexErrorInfo30
        | CodexErrorInfo31
        | CodexErrorInfo32
        | CodexErrorInfo33
        | CodexErrorInfo34
    ) = Field(
        ...,
        description='This translation layer make sure that we expose codex error code in camel case.\n\nWhen an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.',
    )


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class ThreadSpawn(BaseModel):
    agent_nickname: str | None = None
    agent_path: AgentPath | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: ThreadId


class SubAgentSource8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thread_spawn: ThreadSpawn


class SubAgentSource(RootModel[SubAgentSource7 | SubAgentSource8 | SubAgentSource9]):
    root: SubAgentSource7 | SubAgentSource8 | SubAgentSource9


class ThreadItem84(BaseModel):
    content: list[UserInput]
    id: str
    type: Type343 = Field(..., title='UserMessageThreadItemType')


class ThreadItem86(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase21 | None = None
    text: str
    type: Type345 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem90(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type349 = Field(..., title='FileChangeThreadItemType')


class ThreadItem93(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type352 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem94(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type353 = Field(..., title='WebSearchThreadItemType')


class ThreadItem83(
    RootModel[
        ThreadItem84
        | ThreadItem
        | ThreadItem86
        | ThreadItem87
        | ThreadItem88
        | ThreadItem89
        | ThreadItem90
        | ThreadItem91
        | ThreadItem92
        | ThreadItem93
        | ThreadItem94
        | ThreadItem95
        | ThreadItem96
        | ThreadItem97
        | ThreadItem98
        | ThreadItem99
    ]
):
    root: (
        ThreadItem84
        | ThreadItem
        | ThreadItem86
        | ThreadItem87
        | ThreadItem88
        | ThreadItem89
        | ThreadItem90
        | ThreadItem91
        | ThreadItem92
        | ThreadItem93
        | ThreadItem94
        | ThreadItem95
        | ThreadItem96
        | ThreadItem97
        | ThreadItem98
        | ThreadItem99
    )


class TurnError(BaseModel):
    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo28 | None = None
    message: str


class SessionSource11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subAgent: SubAgentSource


class SessionSource8(RootModel[SessionSource | SessionSource10 | SessionSource11]):
    root: SessionSource | SessionSource10 | SessionSource11


class Turn(BaseModel):
    completedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn completed.'
    )
    durationMs: int | None = Field(
        None,
        description='Duration between turn start and completion in milliseconds, if known.',
    )
    error: TurnError | None = Field(
        None, description="Only populated when the Turn's status is failed."
    )
    id: str
    items: list[ThreadItem83] = Field(
        ...,
        description='Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.',
    )
    startedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn started.'
    )
    status: TurnStatus


class Thread(BaseModel):
    agentNickname: str | None = Field(
        None,
        description='Optional random unique nickname assigned to an AgentControl-spawned sub-agent.',
    )
    agentRole: str | None = Field(
        None,
        description='Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.',
    )
    cliVersion: str = Field(
        ..., description='Version of the CLI that created the thread.'
    )
    createdAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was created.'
    )
    cwd: AbsolutePathBuf = Field(
        ..., description='Working directory captured for the thread.'
    )
    ephemeral: bool = Field(
        ...,
        description='Whether the thread is ephemeral and should not be materialized on disk.',
    )
    forkedFromId: str | None = Field(
        None,
        description='Source thread id when this thread was created by forking another thread.',
    )
    gitInfo: GitInfo | None = Field(
        None, description='Optional Git metadata captured when the thread was created.'
    )
    id: str
    modelProvider: str = Field(
        ..., description="Model provider used for this thread (for example, 'openai')."
    )
    name: str | None = Field(None, description='Optional user-facing thread title.')
    path: str | None = Field(None, description='[UNSTABLE] Path to the thread on disk.')
    preview: str = Field(
        ..., description='Usually the first user message in the thread, if available.'
    )
    source: SessionSource8 = Field(
        ...,
        description='Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).',
    )
    status: ThreadStatus = Field(
        ..., description='Current runtime status for the thread.'
    )
    turns: list[Turn] = Field(
        ...,
        description='Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.',
    )
    updatedAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was last updated.'
    )


class ThreadListResponse(BaseModel):
    data: list[Thread]
    nextCursor: str | None = Field(
        None,
        description='Opaque cursor to pass to the next call to continue after the last item. if None, there are no more items to return.',
    )
