# generated by datamodel-codegen:
#   filename:  v2/ThreadUnarchiveResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class AgentPath(RootModel[str]):
    root: str


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CodexErrorInfo(Enum):
    contextWindowExceeded = 'contextWindowExceeded'
    usageLimitExceeded = 'usageLimitExceeded'
    serverOverloaded = 'serverOverloaded'
    internalServerError = 'internalServerError'
    unauthorized = 'unauthorized'
    badRequest = 'badRequest'
    threadRollbackFailed = 'threadRollbackFailed'
    sandboxError = 'sandboxError'
    other = 'other'


class HttpConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo79(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo80(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo81(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo82(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type646(Enum):
    listFiles = 'listFiles'


class CommandAction72(BaseModel):
    command: str
    path: str | None = None
    type: Type646 = Field(..., title='ListFilesCommandActionType')


class Type647(Enum):
    search = 'search'


class CommandAction73(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type647 = Field(..., title='SearchCommandActionType')


class Type648(Enum):
    unknown = 'unknown'


class CommandAction74(BaseModel):
    command: str
    type: Type648 = Field(..., title='UnknownCommandActionType')


class CommandAction70(
    RootModel[CommandAction | CommandAction72 | CommandAction73 | CommandAction74]
):
    root: CommandAction | CommandAction72 | CommandAction73 | CommandAction74


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type649(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type649 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type650(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem41(BaseModel):
    imageUrl: str
    type: Type650 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem39(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem41]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem41


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class GitInfo(BaseModel):
    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class McpToolCallError(BaseModel):
    message: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase47(Enum):
    final_answer = 'final_answer'


class MessagePhase45(RootModel[MessagePhase | MessagePhase47]):
    root: MessagePhase | MessagePhase47 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class NonSteerableTurnKind(Enum):
    review = 'review'
    compact = 'compact'


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type651(Enum):
    add = 'add'


class PatchChangeKind37(BaseModel):
    type: Type651 = Field(..., title='AddPatchChangeKindType')


class Type652(Enum):
    delete = 'delete'


class PatchChangeKind38(BaseModel):
    type: Type652 = Field(..., title='DeletePatchChangeKindType')


class Type653(Enum):
    update = 'update'


class PatchChangeKind39(BaseModel):
    move_path: str | None = None
    type: Type653 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind37 | PatchChangeKind38 | PatchChangeKind39]
):
    root: PatchChangeKind37 | PatchChangeKind38 | PatchChangeKind39


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class SessionSource(Enum):
    cli = 'cli'
    vscode = 'vscode'
    exec = 'exec'
    appServer = 'appServer'
    unknown = 'unknown'


class SessionSource38(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom: str


class SubAgentSource28(Enum):
    review = 'review'
    compact = 'compact'
    memory_consolidation = 'memory_consolidation'


class SubAgentSource30(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    other: str


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class ThreadActiveFlag(Enum):
    waitingOnApproval = 'waitingOnApproval'
    waitingOnUserInput = 'waitingOnUserInput'


class ThreadId(RootModel[str]):
    root: str


class Type654(Enum):
    userMessage = 'userMessage'


class Type655(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type655 = Field(..., title='HookPromptThreadItemType')


class Type656(Enum):
    agentMessage = 'agentMessage'


class Type657(Enum):
    plan = 'plan'


class ThreadItem206(BaseModel):
    id: str
    text: str
    type: Type657 = Field(..., title='PlanThreadItemType')


class Type658(Enum):
    reasoning = 'reasoning'


class ThreadItem207(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type658 = Field(..., title='ReasoningThreadItemType')


class Type659(Enum):
    commandExecution = 'commandExecution'


class ThreadItem208(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction70] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type659 = Field(..., title='CommandExecutionThreadItemType')


class Type660(Enum):
    fileChange = 'fileChange'


class Type661(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem210(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type661 = Field(..., title='McpToolCallThreadItemType')


class Type662(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem211(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem39] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type662 = Field(..., title='DynamicToolCallThreadItemType')


class Type663(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type664(Enum):
    webSearch = 'webSearch'


class Type665(Enum):
    imageView = 'imageView'


class ThreadItem214(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type665 = Field(..., title='ImageViewThreadItemType')


class Type666(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem215(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type666 = Field(..., title='ImageGenerationThreadItemType')


class Type667(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem216(BaseModel):
    id: str
    review: str
    type: Type667 = Field(..., title='EnteredReviewModeThreadItemType')


class Type668(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem217(BaseModel):
    id: str
    review: str
    type: Type668 = Field(..., title='ExitedReviewModeThreadItemType')


class Type669(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem218(BaseModel):
    id: str
    type: Type669 = Field(..., title='ContextCompactionThreadItemType')


class Type670(Enum):
    notLoaded = 'notLoaded'


class ThreadStatus41(BaseModel):
    type: Type670 = Field(..., title='NotLoadedThreadStatusType')


class Type671(Enum):
    idle = 'idle'


class ThreadStatus42(BaseModel):
    type: Type671 = Field(..., title='IdleThreadStatusType')


class Type672(Enum):
    systemError = 'systemError'


class ThreadStatus43(BaseModel):
    type: Type672 = Field(..., title='SystemErrorThreadStatusType')


class Type673(Enum):
    active = 'active'


class ThreadStatus44(BaseModel):
    activeFlags: list[ThreadActiveFlag]
    type: Type673 = Field(..., title='ActiveThreadStatusType')


class ThreadStatus(
    RootModel[ThreadStatus41 | ThreadStatus42 | ThreadStatus43 | ThreadStatus44]
):
    root: ThreadStatus41 | ThreadStatus42 | ThreadStatus43 | ThreadStatus44


class TurnStatus(Enum):
    completed = 'completed'
    interrupted = 'interrupted'
    failed = 'failed'
    inProgress = 'inProgress'


class Type674(Enum):
    text = 'text'


class UserInput66(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type674 = Field(..., title='TextUserInputType')


class Type675(Enum):
    image = 'image'


class UserInput67(BaseModel):
    type: Type675 = Field(..., title='ImageUserInputType')
    url: str


class Type676(Enum):
    localImage = 'localImage'


class UserInput68(BaseModel):
    path: str
    type: Type676 = Field(..., title='LocalImageUserInputType')


class Type677(Enum):
    skill = 'skill'


class UserInput69(BaseModel):
    name: str
    path: str
    type: Type677 = Field(..., title='SkillUserInputType')


class Type678(Enum):
    mention = 'mention'


class UserInput70(BaseModel):
    name: str
    path: str
    type: Type678 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput66 | UserInput67 | UserInput68 | UserInput69 | UserInput70]
):
    root: UserInput66 | UserInput67 | UserInput68 | UserInput69 | UserInput70


class Type679(Enum):
    search = 'search'


class WebSearchAction49(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type679 = Field(..., title='SearchWebSearchActionType')


class Type680(Enum):
    openPage = 'openPage'


class WebSearchAction50(BaseModel):
    type: Type680 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type681(Enum):
    findInPage = 'findInPage'


class WebSearchAction51(BaseModel):
    pattern: str | None = None
    type: Type681 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type682(Enum):
    other = 'other'


class WebSearchAction52(BaseModel):
    type: Type682 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[
        WebSearchAction49 | WebSearchAction50 | WebSearchAction51 | WebSearchAction52
    ]
):
    root: WebSearchAction49 | WebSearchAction50 | WebSearchAction51 | WebSearchAction52


class ActiveTurnNotSteerable(BaseModel):
    turnKind: NonSteerableTurnKind


class CodexErrorInfo83(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CodexErrorInfo77(
    RootModel[
        CodexErrorInfo
        | CodexErrorInfo79
        | CodexErrorInfo80
        | CodexErrorInfo81
        | CodexErrorInfo82
        | CodexErrorInfo83
    ]
):
    root: (
        CodexErrorInfo
        | CodexErrorInfo79
        | CodexErrorInfo80
        | CodexErrorInfo81
        | CodexErrorInfo82
        | CodexErrorInfo83
    ) = Field(
        ...,
        description='This translation layer make sure that we expose codex error code in camel case.\n\nWhen an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.',
    )


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class ThreadSpawn(BaseModel):
    agent_nickname: str | None = None
    agent_path: AgentPath | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: ThreadId


class SubAgentSource29(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thread_spawn: ThreadSpawn


class SubAgentSource(RootModel[SubAgentSource28 | SubAgentSource29 | SubAgentSource30]):
    root: SubAgentSource28 | SubAgentSource29 | SubAgentSource30


class ThreadItem203(BaseModel):
    content: list[UserInput]
    id: str
    type: Type654 = Field(..., title='UserMessageThreadItemType')


class ThreadItem205(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase45 | None = None
    text: str
    type: Type656 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem209(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type660 = Field(..., title='FileChangeThreadItemType')


class ThreadItem212(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type663 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem213(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type664 = Field(..., title='WebSearchThreadItemType')


class ThreadItem202(
    RootModel[
        ThreadItem203
        | ThreadItem
        | ThreadItem205
        | ThreadItem206
        | ThreadItem207
        | ThreadItem208
        | ThreadItem209
        | ThreadItem210
        | ThreadItem211
        | ThreadItem212
        | ThreadItem213
        | ThreadItem214
        | ThreadItem215
        | ThreadItem216
        | ThreadItem217
        | ThreadItem218
    ]
):
    root: (
        ThreadItem203
        | ThreadItem
        | ThreadItem205
        | ThreadItem206
        | ThreadItem207
        | ThreadItem208
        | ThreadItem209
        | ThreadItem210
        | ThreadItem211
        | ThreadItem212
        | ThreadItem213
        | ThreadItem214
        | ThreadItem215
        | ThreadItem216
        | ThreadItem217
        | ThreadItem218
    )


class TurnError(BaseModel):
    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo77 | None = None
    message: str


class SessionSource39(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subAgent: SubAgentSource


class SessionSource36(RootModel[SessionSource | SessionSource38 | SessionSource39]):
    root: SessionSource | SessionSource38 | SessionSource39


class Turn(BaseModel):
    completedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn completed.'
    )
    durationMs: int | None = Field(
        None,
        description='Duration between turn start and completion in milliseconds, if known.',
    )
    error: TurnError | None = Field(
        None, description="Only populated when the Turn's status is failed."
    )
    id: str
    items: list[ThreadItem202] = Field(
        ...,
        description='Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.',
    )
    startedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn started.'
    )
    status: TurnStatus


class Thread(BaseModel):
    agentNickname: str | None = Field(
        None,
        description='Optional random unique nickname assigned to an AgentControl-spawned sub-agent.',
    )
    agentRole: str | None = Field(
        None,
        description='Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.',
    )
    cliVersion: str = Field(
        ..., description='Version of the CLI that created the thread.'
    )
    createdAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was created.'
    )
    cwd: AbsolutePathBuf = Field(
        ..., description='Working directory captured for the thread.'
    )
    ephemeral: bool = Field(
        ...,
        description='Whether the thread is ephemeral and should not be materialized on disk.',
    )
    forkedFromId: str | None = Field(
        None,
        description='Source thread id when this thread was created by forking another thread.',
    )
    gitInfo: GitInfo | None = Field(
        None, description='Optional Git metadata captured when the thread was created.'
    )
    id: str
    modelProvider: str = Field(
        ..., description="Model provider used for this thread (for example, 'openai')."
    )
    name: str | None = Field(None, description='Optional user-facing thread title.')
    path: str | None = Field(None, description='[UNSTABLE] Path to the thread on disk.')
    preview: str = Field(
        ..., description='Usually the first user message in the thread, if available.'
    )
    source: SessionSource36 = Field(
        ...,
        description='Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).',
    )
    status: ThreadStatus = Field(
        ..., description='Current runtime status for the thread.'
    )
    turns: list[Turn] = Field(
        ...,
        description='Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.',
    )
    updatedAt: int = Field(
        ..., description='Unix timestamp (in seconds) when the thread was last updated.'
    )


class ThreadUnarchiveResponse(BaseModel):
    thread: Thread
