# generated by datamodel-codegen:
#   filename:  v2/ThreadListParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, conint


class ThreadSortKey(Enum):
    created_at = 'created_at'
    updated_at = 'updated_at'


class ThreadSourceKind(Enum):
    cli = 'cli'
    vscode = 'vscode'
    exec = 'exec'
    appServer = 'appServer'
    subAgent = 'subAgent'
    subAgentReview = 'subAgentReview'
    subAgentCompact = 'subAgentCompact'
    subAgentThreadSpawn = 'subAgentThreadSpawn'
    subAgentOther = 'subAgentOther'
    unknown = 'unknown'


class ThreadListParams(BaseModel):
    archived: bool | None = Field(
        None,
        description='Optional archived filter; when set to true, only archived threads are returned. If false or null, only non-archived threads are returned.',
    )
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    cwd: str | None = Field(
        None,
        description='Optional cwd filter; when set, only threads whose session cwd exactly matches this path are returned.',
    )
    limit: conint(ge=0) | None = Field(
        None,
        description='Optional page size; defaults to a reasonable server-side value.',
    )
    modelProviders: list[str] | None = Field(
        None,
        description='Optional provider filter; when set, only sessions recorded under these providers are returned. When present but empty, includes all providers.',
    )
    searchTerm: str | None = Field(
        None, description='Optional substring filter for the extracted thread title.'
    )
    sortKey: ThreadSortKey | None = Field(
        None, description='Optional sort key; defaults to created_at.'
    )
    sourceKinds: list[ThreadSourceKind] | None = Field(
        None,
        description='Optional source filter; when set, only sessions from these source kinds are returned. When omitted or empty, defaults to interactive sources.',
    )
