# generated by datamodel-codegen:
#   filename:  v2/ThreadResumeParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class ApprovalsReviewer(Enum):
    user = 'user'
    guardian_subagent = 'guardian_subagent'


class AskForApproval13(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval(RootModel[AskForApproval13 | AskForApproval14]):
    root: AskForApproval13 | AskForApproval14


class Type(Enum):
    input_text = 'input_text'


class ContentItem(BaseModel):
    text: str
    type: Type = Field(..., title='InputTextContentItemType')


class Type451(Enum):
    input_image = 'input_image'


class ContentItem10(BaseModel):
    image_url: str
    type: Type451 = Field(..., title='InputImageContentItemType')


class Type452(Enum):
    output_text = 'output_text'


class ContentItem11(BaseModel):
    text: str
    type: Type452 = Field(..., title='OutputTextContentItemType')


class ContentItem8(RootModel[ContentItem | ContentItem10 | ContentItem11]):
    root: ContentItem | ContentItem10 | ContentItem11


class Type453(Enum):
    input_text = 'input_text'


class FunctionCallOutputContentItem5(BaseModel):
    text: str
    type: Type453 = Field(..., title='InputTextFunctionCallOutputContentItemType')


class Type454(Enum):
    input_image = 'input_image'


class GhostCommit(BaseModel):
    id: str
    parent: str | None = None
    preexisting_untracked_dirs: list[str]
    preexisting_untracked_files: list[str]


class ImageDetail(Enum):
    auto = 'auto'
    low = 'low'
    high = 'high'
    original = 'original'


class Type455(Enum):
    exec = 'exec'


class LocalShellAction(BaseModel):
    command: list[str]
    env: dict[str, Any] | None = None
    timeout_ms: conint(ge=0) | None = None
    type: Type455 = Field(..., title='ExecLocalShellActionType')
    user: str | None = None
    working_directory: str | None = None


class LocalShellAction4(RootModel[LocalShellAction]):
    root: LocalShellAction


class LocalShellStatus(Enum):
    completed = 'completed'
    in_progress = 'in_progress'
    incomplete = 'incomplete'


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase32(Enum):
    final_answer = 'final_answer'


class MessagePhase30(RootModel[MessagePhase | MessagePhase32]):
    root: MessagePhase | MessagePhase32 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class Personality(Enum):
    none = 'none'
    friendly = 'friendly'
    pragmatic = 'pragmatic'


class Type456(Enum):
    reasoning_text = 'reasoning_text'


class ReasoningItemContent(BaseModel):
    text: str
    type: Type456 = Field(..., title='ReasoningTextReasoningItemContentType')


class Type457(Enum):
    text = 'text'


class ReasoningItemContent8(BaseModel):
    text: str
    type: Type457 = Field(..., title='TextReasoningItemContentType')


class ReasoningItemContent6(RootModel[ReasoningItemContent | ReasoningItemContent8]):
    root: ReasoningItemContent | ReasoningItemContent8


class Type458(Enum):
    summary_text = 'summary_text'


class ReasoningItemReasoningSummary(BaseModel):
    text: str
    type: Type458 = Field(..., title='SummaryTextReasoningItemReasoningSummaryType')


class ReasoningItemReasoningSummary4(RootModel[ReasoningItemReasoningSummary]):
    root: ReasoningItemReasoningSummary


class Type459(Enum):
    message = 'message'


class ResponseItem29(BaseModel):
    content: list[ContentItem8]
    end_turn: bool | None = None
    id: str | None = None
    phase: MessagePhase30 | None = None
    role: str
    type: Type459 = Field(..., title='MessageResponseItemType')


class Type460(Enum):
    reasoning = 'reasoning'


class ResponseItem30(BaseModel):
    content: list[ReasoningItemContent6] | None = None
    encrypted_content: str | None = None
    summary: list[ReasoningItemReasoningSummary4]
    type: Type460 = Field(..., title='ReasoningResponseItemType')


class Type461(Enum):
    local_shell_call = 'local_shell_call'


class ResponseItem31(BaseModel):
    action: LocalShellAction4
    call_id: str | None = Field(None, description='Set when using the Responses API.')
    id: str | None = Field(
        None,
        description='Legacy id field retained for compatibility with older payloads.',
    )
    status: LocalShellStatus
    type: Type461 = Field(..., title='LocalShellCallResponseItemType')


class Type462(Enum):
    function_call = 'function_call'


class ResponseItem32(BaseModel):
    arguments: str
    call_id: str
    id: str | None = None
    name: str
    namespace: str | None = None
    type: Type462 = Field(..., title='FunctionCallResponseItemType')


class Type463(Enum):
    tool_search_call = 'tool_search_call'


class ResponseItem33(BaseModel):
    arguments: Any
    call_id: str | None = None
    execution: str
    id: str | None = None
    status: str | None = None
    type: Type463 = Field(..., title='ToolSearchCallResponseItemType')


class Type464(Enum):
    function_call_output = 'function_call_output'


class Type465(Enum):
    custom_tool_call = 'custom_tool_call'


class ResponseItem35(BaseModel):
    call_id: str
    id: str | None = None
    input: str
    name: str
    status: str | None = None
    type: Type465 = Field(..., title='CustomToolCallResponseItemType')


class Type466(Enum):
    custom_tool_call_output = 'custom_tool_call_output'


class Type467(Enum):
    tool_search_output = 'tool_search_output'


class ResponseItem37(BaseModel):
    call_id: str | None = None
    execution: str
    status: str
    tools: list[Any]
    type: Type467 = Field(..., title='ToolSearchOutputResponseItemType')


class Type468(Enum):
    web_search_call = 'web_search_call'


class Type469(Enum):
    image_generation_call = 'image_generation_call'


class ResponseItem39(BaseModel):
    id: str
    result: str
    revised_prompt: str | None = None
    status: str
    type: Type469 = Field(..., title='ImageGenerationCallResponseItemType')


class Type470(Enum):
    ghost_snapshot = 'ghost_snapshot'


class ResponseItem40(BaseModel):
    ghost_commit: GhostCommit
    type: Type470 = Field(..., title='GhostSnapshotResponseItemType')


class Type471(Enum):
    compaction = 'compaction'


class ResponseItem41(BaseModel):
    encrypted_content: str
    type: Type471 = Field(..., title='CompactionResponseItemType')


class Type472(Enum):
    other = 'other'


class ResponseItem42(BaseModel):
    type: Type472 = Field(..., title='OtherResponseItemType')


class Type473(Enum):
    search = 'search'


class ResponsesApiWebSearchAction9(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type473 = Field(..., title='SearchResponsesApiWebSearchActionType')


class Type474(Enum):
    open_page = 'open_page'


class ResponsesApiWebSearchAction10(BaseModel):
    type: Type474 = Field(..., title='OpenPageResponsesApiWebSearchActionType')
    url: str | None = None


class Type475(Enum):
    find_in_page = 'find_in_page'


class ResponsesApiWebSearchAction11(BaseModel):
    pattern: str | None = None
    type: Type475 = Field(..., title='FindInPageResponsesApiWebSearchActionType')
    url: str | None = None


class Type476(Enum):
    other = 'other'


class ResponsesApiWebSearchAction12(BaseModel):
    type: Type476 = Field(..., title='OtherResponsesApiWebSearchActionType')


class ResponsesApiWebSearchAction(
    RootModel[
        ResponsesApiWebSearchAction9
        | ResponsesApiWebSearchAction10
        | ResponsesApiWebSearchAction11
        | ResponsesApiWebSearchAction12
    ]
):
    root: (
        ResponsesApiWebSearchAction9
        | ResponsesApiWebSearchAction10
        | ResponsesApiWebSearchAction11
        | ResponsesApiWebSearchAction12
    )


class SandboxMode(Enum):
    read_only = 'read-only'
    workspace_write = 'workspace-write'
    danger_full_access = 'danger-full-access'


class ServiceTier(Enum):
    fast = 'fast'
    flex = 'flex'


class FunctionCallOutputContentItem6(BaseModel):
    detail: ImageDetail | None = None
    image_url: str
    type: Type454 = Field(..., title='InputImageFunctionCallOutputContentItemType')


class FunctionCallOutputContentItem(
    RootModel[FunctionCallOutputContentItem5 | FunctionCallOutputContentItem6]
):
    root: FunctionCallOutputContentItem5 | FunctionCallOutputContentItem6 = Field(
        ...,
        description='Responses API compatible content items that can be returned by a tool call. This is a subset of ContentItem with the types we support as function call outputs.',
    )


class ResponseItem38(BaseModel):
    action: ResponsesApiWebSearchAction | None = None
    id: str | None = None
    status: str | None = None
    type: Type468 = Field(..., title='WebSearchCallResponseItemType')


class FunctionCallOutputBody(RootModel[str | list[FunctionCallOutputContentItem]]):
    root: str | list[FunctionCallOutputContentItem]


class ResponseItem34(BaseModel):
    call_id: str
    output: FunctionCallOutputBody
    type: Type464 = Field(..., title='FunctionCallOutputResponseItemType')


class ResponseItem36(BaseModel):
    call_id: str
    name: str | None = None
    output: FunctionCallOutputBody
    type: Type466 = Field(..., title='CustomToolCallOutputResponseItemType')


class ResponseItem(
    RootModel[
        ResponseItem29
        | ResponseItem30
        | ResponseItem31
        | ResponseItem32
        | ResponseItem33
        | ResponseItem34
        | ResponseItem35
        | ResponseItem36
        | ResponseItem37
        | ResponseItem38
        | ResponseItem39
        | ResponseItem40
        | ResponseItem41
        | ResponseItem42
    ]
):
    root: (
        ResponseItem29
        | ResponseItem30
        | ResponseItem31
        | ResponseItem32
        | ResponseItem33
        | ResponseItem34
        | ResponseItem35
        | ResponseItem36
        | ResponseItem37
        | ResponseItem38
        | ResponseItem39
        | ResponseItem40
        | ResponseItem41
        | ResponseItem42
    )


class ThreadResumeParams(BaseModel):
    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this thread and subsequent turns.',
    )
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    history: list[ResponseItem] | None = Field(
        None,
        description='[UNSTABLE] FOR CODEX CLOUD - DO NOT USE. If specified, the thread will be resumed with the provided history instead of loaded from disk.',
    )
    model: str | None = Field(
        None, description='Configuration overrides for the resumed thread, if any.'
    )
    modelProvider: str | None = None
    path: str | None = Field(
        None,
        description='[UNSTABLE] Specify the rollout path to resume from. If specified, the thread_id param will be ignored.',
    )
    persistExtendedHistory: bool | None = Field(
        False,
        description='If true, persist additional rollout EventMsg variants required to reconstruct a richer thread history on subsequent resume/fork/read.',
    )
    personality: Personality | None = None
    sandbox: SandboxMode | None = None
    serviceTier: ServiceTier | None = None
    threadId: str
