# generated by datamodel-codegen:
#   filename:  v2/ThreadRealtimeTranscriptDeltaNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ThreadRealtimeTranscriptDeltaNotification(BaseModel):
    delta: str = Field(
        ..., description='Live transcript delta from the realtime event.'
    )
    role: str
    threadId: str
