# generated by datamodel-codegen:
#   filename:  v2/ThreadRealtimeTranscriptDoneNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ThreadRealtimeTranscriptDoneNotification(BaseModel):
    role: str
    text: str = Field(..., description='Final complete text for the transcript part.')
    threadId: str
