# generated by datamodel-codegen:
#   filename:  v2/ThreadRealtimeListVoicesResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class RealtimeVoice(Enum):
    alloy = 'alloy'
    arbor = 'arbor'
    ash = 'ash'
    ballad = 'ballad'
    breeze = 'breeze'
    cedar = 'cedar'
    coral = 'coral'
    cove = 'cove'
    echo = 'echo'
    ember = 'ember'
    juniper = 'juniper'
    maple = 'maple'
    marin = 'marin'
    sage = 'sage'
    shimmer = 'shimmer'
    sol = 'sol'
    spruce = 'spruce'
    vale = 'vale'
    verse = 'verse'


class RealtimeVoicesList(BaseModel):
    defaultV1: RealtimeVoice
    defaultV2: RealtimeVoice
    v1: list[RealtimeVoice]
    v2: list[RealtimeVoice]


class ThreadRealtimeListVoicesResponse(BaseModel):
    voices: RealtimeVoicesList
