# generated by datamodel-codegen:
#   filename:  v2/ThreadIncrementElicitationResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class ThreadIncrementElicitationResponse(BaseModel):
    count: conint(ge=0) = Field(
        ..., description='Current out-of-band elicitation count after the increment.'
    )
    paused: bool = Field(
        ...,
        description='Whether timeout accounting is paused after applying the increment.',
    )
