# generated by datamodel-codegen:
#   filename:  v2/WindowsSandboxSetupCompletedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class WindowsSandboxSetupMode(Enum):
    elevated = 'elevated'
    unelevated = 'unelevated'


class WindowsSandboxSetupCompletedNotification(BaseModel):
    error: str | None = None
    mode: WindowsSandboxSetupMode
    success: bool
