# generated by datamodel-codegen:
#   filename:  v2/CancelLoginAccountResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class CancelLoginAccountStatus(Enum):
    canceled = 'canceled'
    notFound = 'notFound'


class CancelLoginAccountResponse(BaseModel):
    status: CancelLoginAccountStatus
