# generated by datamodel-codegen:
#   filename:  v2/ConfigWriteResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class Type(Enum):
    mdm = 'mdm'


class ConfigLayerSource8(BaseModel):
    domain: str
    key: str
    type: Type = Field(..., title='MdmConfigLayerSourceType')


class Type69(Enum):
    system = 'system'


class ConfigLayerSource9(BaseModel):
    file: AbsolutePathBuf = Field(
        ...,
        description='This is the path to the system config.toml file, though it is not guaranteed to exist.',
    )
    type: Type69 = Field(..., title='SystemConfigLayerSourceType')


class Type70(Enum):
    user = 'user'


class ConfigLayerSource10(BaseModel):
    file: AbsolutePathBuf = Field(
        ...,
        description="This is the path to the user's config.toml file, though it is not guaranteed to exist.",
    )
    type: Type70 = Field(..., title='UserConfigLayerSourceType')


class Type71(Enum):
    project = 'project'


class ConfigLayerSource11(BaseModel):
    dotCodexFolder: AbsolutePathBuf
    type: Type71 = Field(..., title='ProjectConfigLayerSourceType')


class Type72(Enum):
    sessionFlags = 'sessionFlags'


class ConfigLayerSource12(BaseModel):
    type: Type72 = Field(..., title='SessionFlagsConfigLayerSourceType')


class Type73(Enum):
    legacyManagedConfigTomlFromFile = 'legacyManagedConfigTomlFromFile'


class ConfigLayerSource13(BaseModel):
    file: AbsolutePathBuf
    type: Type73 = Field(
        ..., title='LegacyManagedConfigTomlFromFileConfigLayerSourceType'
    )


class Type74(Enum):
    legacyManagedConfigTomlFromMdm = 'legacyManagedConfigTomlFromMdm'


class ConfigLayerSource14(BaseModel):
    type: Type74 = Field(
        ..., title='LegacyManagedConfigTomlFromMdmConfigLayerSourceType'
    )


class ConfigLayerSource(
    RootModel[
        ConfigLayerSource8
        | ConfigLayerSource9
        | ConfigLayerSource10
        | ConfigLayerSource11
        | ConfigLayerSource12
        | ConfigLayerSource13
        | ConfigLayerSource14
    ]
):
    root: (
        ConfigLayerSource8
        | ConfigLayerSource9
        | ConfigLayerSource10
        | ConfigLayerSource11
        | ConfigLayerSource12
        | ConfigLayerSource13
        | ConfigLayerSource14
    )


class WriteStatus(Enum):
    ok = 'ok'
    okOverridden = 'okOverridden'


class ConfigLayerMetadata(BaseModel):
    name: ConfigLayerSource
    version: str


class OverriddenMetadata(BaseModel):
    effectiveValue: Any
    message: str
    overridingLayer: ConfigLayerMetadata


class ConfigWriteResponse(BaseModel):
    filePath: AbsolutePathBuf = Field(
        ..., description='Canonical path to the config file that was written.'
    )
    overriddenMetadata: OverriddenMetadata | None = None
    status: WriteStatus
    version: str
