# generated by datamodel-codegen:
#   filename:  v2/ConfigRequirementsReadResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class ApprovalsReviewer(Enum):
    user = 'user'
    guardian_subagent = 'guardian_subagent'


class AskForApproval(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval6(RootModel[AskForApproval | AskForApproval8]):
    root: AskForApproval | AskForApproval8


class NetworkDomainPermission(Enum):
    allow = 'allow'
    deny = 'deny'


class NetworkRequirements(BaseModel):
    allowLocalBinding: bool | None = None
    allowUnixSockets: list[str] | None = Field(
        None, description='Legacy compatibility view derived from `unix_sockets`.'
    )
    allowUpstreamProxy: bool | None = None
    allowedDomains: list[str] | None = Field(
        None, description='Legacy compatibility view derived from `domains`.'
    )
    dangerouslyAllowAllUnixSockets: bool | None = None
    dangerouslyAllowNonLoopbackProxy: bool | None = None
    deniedDomains: list[str] | None = Field(
        None, description='Legacy compatibility view derived from `domains`.'
    )
    domains: dict[str, Any] | None = Field(
        None, description='Canonical network permission map for `experimental_network`.'
    )
    enabled: bool | None = None
    httpPort: conint(ge=0) | None = None
    managedAllowedDomainsOnly: bool | None = Field(
        None,
        description='When true, only managed allowlist entries are respected while managed network enforcement is active.',
    )
    socksPort: conint(ge=0) | None = None
    unixSockets: dict[str, Any] | None = Field(
        None,
        description='Canonical unix socket permission map for `experimental_network`.',
    )


class NetworkUnixSocketPermission(Enum):
    allow = 'allow'
    none = 'none'


class ResidencyRequirement(Enum):
    us = 'us'


class SandboxMode(Enum):
    read_only = 'read-only'
    workspace_write = 'workspace-write'
    danger_full_access = 'danger-full-access'


class WebSearchMode(Enum):
    disabled = 'disabled'
    cached = 'cached'
    live = 'live'


class ConfigRequirements(BaseModel):
    allowedApprovalPolicies: list[AskForApproval6] | None = None
    allowedApprovalsReviewers: list[ApprovalsReviewer] | None = None
    allowedSandboxModes: list[SandboxMode] | None = None
    allowedWebSearchModes: list[WebSearchMode] | None = None
    enforceResidency: ResidencyRequirement | None = None
    featureRequirements: dict[str, Any] | None = None
    network: NetworkRequirements | None = None


class ConfigRequirementsReadResponse(BaseModel):
    requirements: ConfigRequirements | None = Field(
        None,
        description='Null if no requirements are configured (e.g. no requirements.toml/MDM entries).',
    )
