# generated by datamodel-codegen:
#   filename:  v2/DeprecationNoticeNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DeprecationNoticeNotification(BaseModel):
    details: str | None = Field(
        None,
        description='Optional extra guidance, such as migration steps or rationale.',
    )
    summary: str = Field(..., description='Concise summary of what is deprecated.')
