# generated by datamodel-codegen:
#   filename:  v2/ExternalAgentConfigDetectParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ExternalAgentConfigDetectParams(BaseModel):
    cwds: list[str] | None = Field(
        None,
        description='Zero or more working directories to include for repo-scoped detection.',
    )
    includeHome: bool | None = Field(
        None,
        description="If true, include detection under the user's home (~/.claude, ~/.codex, etc.).",
    )
