# generated by datamodel-codegen:
#   filename:  v2/FsUnwatchParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FsUnwatchParams(BaseModel):
    watchId: str = Field(
        ..., description='Watch identifier previously provided to `fs/watch`.'
    )
