# generated by datamodel-codegen:
#   filename:  v2/LoginAccountParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Type(Enum):
    apiKey = 'apiKey'


class LoginAccountParams5(BaseModel):
    apiKey: str
    type: Type = Field(..., title='ApiKeyv2::LoginAccountParamsType')


class Type162(Enum):
    chatgpt = 'chatgpt'


class LoginAccountParams6(BaseModel):
    type: Type162 = Field(..., title='Chatgptv2::LoginAccountParamsType')


class Type163(Enum):
    chatgptDeviceCode = 'chatgptDeviceCode'


class LoginAccountParams7(BaseModel):
    type: Type163 = Field(..., title='ChatgptDeviceCodev2::LoginAccountParamsType')


class Type164(Enum):
    chatgptAuthTokens = 'chatgptAuthTokens'


class LoginAccountParams8(BaseModel):
    accessToken: str = Field(
        ...,
        description='Access token (JWT) supplied by the client. This token is used for backend API requests and email extraction.',
    )
    chatgptAccountId: str = Field(
        ..., description='Workspace/account identifier supplied by the client.'
    )
    chatgptPlanType: str | None = Field(
        None,
        description='Optional plan type supplied by the client.\n\nWhen `null`, Codex attempts to derive the plan type from access-token claims. If unavailable, the plan defaults to `unknown`.',
    )
    type: Type164 = Field(..., title='ChatgptAuthTokensv2::LoginAccountParamsType')


class LoginAccountParams(
    RootModel[
        LoginAccountParams5
        | LoginAccountParams6
        | LoginAccountParams7
        | LoginAccountParams8
    ]
):
    root: (
        LoginAccountParams5
        | LoginAccountParams6
        | LoginAccountParams7
        | LoginAccountParams8
    ) = Field(..., title='LoginAccountParams')
