# generated by datamodel-codegen:
#   filename:  v2/McpServerStatusUpdatedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class McpServerStartupState(Enum):
    starting = 'starting'
    ready = 'ready'
    failed = 'failed'
    cancelled = 'cancelled'


class McpServerStatusUpdatedNotification(BaseModel):
    error: str | None = None
    name: str
    status: McpServerStartupState
