# generated by datamodel-codegen:
#   filename:  v2/MockExperimentalMethodParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class MockExperimentalMethodParams(BaseModel):
    value: str | None = Field(None, description='Test-only payload field.')
