# generated by datamodel-codegen:
#   filename:  v2/MockExperimentalMethodResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class MockExperimentalMethodResponse(BaseModel):
    echoed: str | None = Field(None, description='Echoes the input `value`.')
