# generated by datamodel-codegen:
#   filename:  v2/PluginListResponse.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class MarketplaceInterface(BaseModel):
    displayName: str | None = None


class MarketplaceLoadErrorInfo(BaseModel):
    marketplacePath: AbsolutePathBuf
    message: str


class PluginAuthPolicy(Enum):
    ON_INSTALL = 'ON_INSTALL'
    ON_USE = 'ON_USE'


class PluginInstallPolicy(Enum):
    NOT_AVAILABLE = 'NOT_AVAILABLE'
    AVAILABLE = 'AVAILABLE'
    INSTALLED_BY_DEFAULT = 'INSTALLED_BY_DEFAULT'


class PluginInterface(BaseModel):
    brandColor: str | None = None
    capabilities: list[str]
    category: str | None = None
    composerIcon: AbsolutePathBuf | None = None
    defaultPrompt: list[str] | None = Field(
        None,
        description='Starter prompts for the plugin. Capped at 3 entries with a maximum of 128 characters per entry.',
    )
    developerName: str | None = None
    displayName: str | None = None
    logo: AbsolutePathBuf | None = None
    longDescription: str | None = None
    privacyPolicyUrl: str | None = None
    screenshots: list[AbsolutePathBuf]
    shortDescription: str | None = None
    termsOfServiceUrl: str | None = None
    websiteUrl: str | None = None


class Type(Enum):
    local = 'local'


class PluginSource1(BaseModel):
    path: AbsolutePathBuf
    type: Type = Field(..., title='LocalPluginSourceType')


class PluginSource(RootModel[PluginSource1]):
    root: PluginSource1


class PluginSummary(BaseModel):
    authPolicy: PluginAuthPolicy
    enabled: bool
    id: str
    installPolicy: PluginInstallPolicy
    installed: bool
    interface: PluginInterface | None = None
    name: str
    source: PluginSource


class PluginMarketplaceEntry(BaseModel):
    interface: MarketplaceInterface | None = None
    name: str
    path: AbsolutePathBuf
    plugins: list[PluginSummary]


class PluginListResponse(BaseModel):
    featuredPluginIds: list[str] | None = []
    marketplaceLoadErrors: list[MarketplaceLoadErrorInfo] | None = Field(
        [], validate_default=True
    )
    marketplaces: list[PluginMarketplaceEntry]
    remoteSyncError: str | None = None
