# generated by datamodel-codegen:
#   filename:  v2/ThreadRealtimeAppendAudioParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class ThreadRealtimeAudioChunk(BaseModel):
    data: str
    itemId: str | None = None
    numChannels: conint(ge=0)
    sampleRate: conint(ge=0)
    samplesPerChannel: conint(ge=0) | None = None


class ThreadRealtimeAppendAudioParams(BaseModel):
    audio: ThreadRealtimeAudioChunk
    threadId: str
