# generated by datamodel-codegen:
#   filename:  v2/ThreadForkParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ApprovalsReviewer(Enum):
    user = 'user'
    guardian_subagent = 'guardian_subagent'


class AskForApproval9(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval(RootModel[AskForApproval9 | AskForApproval10]):
    root: AskForApproval9 | AskForApproval10


class SandboxMode(Enum):
    read_only = 'read-only'
    workspace_write = 'workspace-write'
    danger_full_access = 'danger-full-access'


class ServiceTier(Enum):
    fast = 'fast'
    flex = 'flex'


class ThreadForkParams(BaseModel):
    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this thread and subsequent turns.',
    )
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    ephemeral: bool | None = None
    model: str | None = Field(
        None, description='Configuration overrides for the forked thread, if any.'
    )
    modelProvider: str | None = None
    path: str | None = Field(
        None,
        description='[UNSTABLE] Specify the rollout path to fork from. If specified, the thread_id param will be ignored.',
    )
    persistExtendedHistory: bool | None = Field(
        False,
        description='If true, persist additional rollout EventMsg variants required to reconstruct a richer thread history on subsequent resume/fork/read.',
    )
    sandbox: SandboxMode | None = None
    serviceTier: ServiceTier | None = None
    threadId: str
