# generated by datamodel-codegen:
#   filename:  v2/ThreadLoadedListParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class ThreadLoadedListParams(BaseModel):
    cursor: str | None = Field(
        None, description='Opaque pagination cursor returned by a previous call.'
    )
    limit: conint(ge=0) | None = Field(
        None, description='Optional page size; defaults to no limit.'
    )
