# generated by datamodel-codegen:
#   filename:  v2/ThreadStartParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ApprovalsReviewer(Enum):
    user = 'user'
    guardian_subagent = 'guardian_subagent'


class AskForApproval17(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval(RootModel[AskForApproval17 | AskForApproval18]):
    root: AskForApproval17 | AskForApproval18


class DynamicToolSpec(BaseModel):
    deferLoading: bool | None = None
    description: str
    inputSchema: Any
    name: str


class Personality(Enum):
    none = 'none'
    friendly = 'friendly'
    pragmatic = 'pragmatic'


class SandboxMode(Enum):
    read_only = 'read-only'
    workspace_write = 'workspace-write'
    danger_full_access = 'danger-full-access'


class ServiceTier(Enum):
    fast = 'fast'
    flex = 'flex'


class ThreadStartSource(Enum):
    startup = 'startup'
    clear = 'clear'


class ThreadStartParams(BaseModel):
    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this thread and subsequent turns.',
    )
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    dynamicTools: list[DynamicToolSpec] | None = None
    ephemeral: bool | None = None
    experimentalRawEvents: bool | None = Field(
        False,
        description='If true, opt into emitting raw Responses API items on the event stream. This is for internal use only (e.g. Codex Cloud).',
    )
    mockExperimentalField: str | None = Field(
        None,
        description='Test-only experimental field used to validate experimental gating and schema filtering behavior in a stable way.',
    )
    model: str | None = None
    modelProvider: str | None = None
    persistExtendedHistory: bool | None = Field(
        False,
        description='If true, persist additional rollout EventMsg variants required to reconstruct a richer thread history on resume/fork/read.',
    )
    personality: Personality | None = None
    sandbox: SandboxMode | None = None
    serviceName: str | None = None
    serviceTier: ServiceTier | None = None
    sessionStartSource: ThreadStartSource | None = None
