# generated by datamodel-codegen:
#   filename:  v2/ThreadRealtimeItemAddedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class ThreadRealtimeItemAddedNotification(BaseModel):
    item: Any
    threadId: str
