# generated by datamodel-codegen:
#   filename:  v2/ThreadStatusChangedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class ThreadActiveFlag(Enum):
    waitingOnApproval = 'waitingOnApproval'
    waitingOnUserInput = 'waitingOnUserInput'


class Type(Enum):
    notLoaded = 'notLoaded'


class ThreadStatus37(BaseModel):
    type: Type = Field(..., title='NotLoadedThreadStatusType')


class Type642(Enum):
    idle = 'idle'


class ThreadStatus38(BaseModel):
    type: Type642 = Field(..., title='IdleThreadStatusType')


class Type643(Enum):
    systemError = 'systemError'


class ThreadStatus39(BaseModel):
    type: Type643 = Field(..., title='SystemErrorThreadStatusType')


class Type644(Enum):
    active = 'active'


class ThreadStatus40(BaseModel):
    activeFlags: list[ThreadActiveFlag]
    type: Type644 = Field(..., title='ActiveThreadStatusType')


class ThreadStatus(
    RootModel[ThreadStatus37 | ThreadStatus38 | ThreadStatus39 | ThreadStatus40]
):
    root: ThreadStatus37 | ThreadStatus38 | ThreadStatus39 | ThreadStatus40


class ThreadStatusChangedNotification(BaseModel):
    status: ThreadStatus
    threadId: str
