# generated by datamodel-codegen:
#   filename:  v2/TurnSteerParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class Type(Enum):
    text = 'text'


class UserInput91(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type = Field(..., title='TextUserInputType')


class Type797(Enum):
    image = 'image'


class UserInput92(BaseModel):
    type: Type797 = Field(..., title='ImageUserInputType')
    url: str


class Type798(Enum):
    localImage = 'localImage'


class UserInput93(BaseModel):
    path: str
    type: Type798 = Field(..., title='LocalImageUserInputType')


class Type799(Enum):
    skill = 'skill'


class UserInput94(BaseModel):
    name: str
    path: str
    type: Type799 = Field(..., title='SkillUserInputType')


class Type800(Enum):
    mention = 'mention'


class UserInput95(BaseModel):
    name: str
    path: str
    type: Type800 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput91 | UserInput92 | UserInput93 | UserInput94 | UserInput95]
):
    root: UserInput91 | UserInput92 | UserInput93 | UserInput94 | UserInput95


class TurnSteerParams(BaseModel):
    expectedTurnId: str = Field(
        ...,
        description='Required active turn id precondition. The request fails when it does not match the currently active turn.',
    )
    input: list[UserInput]
    responsesapiClientMetadata: dict[str, Any] | None = Field(
        None, description='Optional turn-scoped Responses API client metadata.'
    )
    threadId: str
