# generated by datamodel-codegen:
#   filename:  v2/TurnStartParams.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class ApprovalsReviewer(Enum):
    user = 'user'
    guardian_subagent = 'guardian_subagent'


class AskForApproval21(Enum):
    untrusted = 'untrusted'
    on_failure = 'on-failure'
    on_request = 'on-request'
    never = 'never'


class Granular(BaseModel):
    mcp_elicitations: bool
    request_permissions: bool | None = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool | None = False


class AskForApproval22(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    granular: Granular


class AskForApproval(RootModel[AskForApproval21 | AskForApproval22]):
    root: AskForApproval21 | AskForApproval22


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class ModeKind(Enum):
    plan = 'plan'
    default = 'default'


class NetworkAccess(Enum):
    restricted = 'restricted'
    enabled = 'enabled'


class Personality(Enum):
    none = 'none'
    friendly = 'friendly'
    pragmatic = 'pragmatic'


class Type(Enum):
    restricted = 'restricted'


class ReadOnlyAccess(BaseModel):
    includePlatformDefaults: bool | None = True
    readableRoots: list[AbsolutePathBuf] | None = Field([], validate_default=True)
    type: Type = Field(..., title='RestrictedReadOnlyAccessType')


class Type718(Enum):
    fullAccess = 'fullAccess'


class ReadOnlyAccess17(BaseModel):
    type: Type718 = Field(..., title='FullAccessReadOnlyAccessType')


class ReadOnlyAccess15(RootModel[ReadOnlyAccess | ReadOnlyAccess17]):
    root: ReadOnlyAccess | ReadOnlyAccess17


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class ReasoningSummary5(Enum):
    auto = 'auto'
    concise = 'concise'
    detailed = 'detailed'


class ReasoningSummary6(Enum):
    none = 'none'


class ReasoningSummary(RootModel[ReasoningSummary5 | ReasoningSummary6]):
    root: ReasoningSummary5 | ReasoningSummary6 = Field(
        ...,
        description="A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries",
    )


class Type719(Enum):
    dangerFullAccess = 'dangerFullAccess'


class SandboxPolicy21(BaseModel):
    type: Type719 = Field(..., title='DangerFullAccessSandboxPolicyType')


class Type720(Enum):
    readOnly = 'readOnly'


class SandboxPolicy22(BaseModel):
    access: ReadOnlyAccess15 | None = Field(
        {'type': 'fullAccess'}, validate_default=True
    )
    networkAccess: bool | None = False
    type: Type720 = Field(..., title='ReadOnlySandboxPolicyType')


class Type721(Enum):
    externalSandbox = 'externalSandbox'


class SandboxPolicy23(BaseModel):
    networkAccess: NetworkAccess | None = 'restricted'
    type: Type721 = Field(..., title='ExternalSandboxSandboxPolicyType')


class Type722(Enum):
    workspaceWrite = 'workspaceWrite'


class SandboxPolicy24(BaseModel):
    excludeSlashTmp: bool | None = False
    excludeTmpdirEnvVar: bool | None = False
    networkAccess: bool | None = False
    readOnlyAccess: ReadOnlyAccess15 | None = Field(
        {'type': 'fullAccess'}, validate_default=True
    )
    type: Type722 = Field(..., title='WorkspaceWriteSandboxPolicyType')
    writableRoots: list[AbsolutePathBuf] | None = Field([], validate_default=True)


class SandboxPolicy(
    RootModel[SandboxPolicy21 | SandboxPolicy22 | SandboxPolicy23 | SandboxPolicy24]
):
    root: SandboxPolicy21 | SandboxPolicy22 | SandboxPolicy23 | SandboxPolicy24


class ServiceTier(Enum):
    fast = 'fast'
    flex = 'flex'


class Settings(BaseModel):
    developer_instructions: str | None = None
    model: str
    reasoning_effort: ReasoningEffort | None = None


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class Type723(Enum):
    text = 'text'


class UserInput76(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type723 = Field(..., title='TextUserInputType')


class Type724(Enum):
    image = 'image'


class UserInput77(BaseModel):
    type: Type724 = Field(..., title='ImageUserInputType')
    url: str


class Type725(Enum):
    localImage = 'localImage'


class UserInput78(BaseModel):
    path: str
    type: Type725 = Field(..., title='LocalImageUserInputType')


class Type726(Enum):
    skill = 'skill'


class UserInput79(BaseModel):
    name: str
    path: str
    type: Type726 = Field(..., title='SkillUserInputType')


class Type727(Enum):
    mention = 'mention'


class UserInput80(BaseModel):
    name: str
    path: str
    type: Type727 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput76 | UserInput77 | UserInput78 | UserInput79 | UserInput80]
):
    root: UserInput76 | UserInput77 | UserInput78 | UserInput79 | UserInput80


class CollaborationMode(BaseModel):
    mode: ModeKind
    settings: Settings


class TurnStartParams(BaseModel):
    approvalPolicy: AskForApproval | None = Field(
        None,
        description='Override the approval policy for this turn and subsequent turns.',
    )
    approvalsReviewer: ApprovalsReviewer | None = Field(
        None,
        description='Override where approval requests are routed for review on this turn and subsequent turns.',
    )
    collaborationMode: CollaborationMode | None = Field(
        None,
        description='EXPERIMENTAL - Set a pre-set collaboration mode. Takes precedence over model, reasoning_effort, and developer instructions if set.\n\nFor `collaboration_mode.settings.developer_instructions`, `null` means "use the built-in instructions for the selected mode".',
    )
    cwd: str | None = Field(
        None,
        description='Override the working directory for this turn and subsequent turns.',
    )
    effort: ReasoningEffort | None = Field(
        None,
        description='Override the reasoning effort for this turn and subsequent turns.',
    )
    input: list[UserInput]
    model: str | None = Field(
        None, description='Override the model for this turn and subsequent turns.'
    )
    outputSchema: Any | None = Field(
        None,
        description='Optional JSON Schema used to constrain the final assistant message for this turn.',
    )
    personality: Personality | None = Field(
        None, description='Override the personality for this turn and subsequent turns.'
    )
    responsesapiClientMetadata: dict[str, Any] | None = Field(
        None, description='Optional turn-scoped Responses API client metadata.'
    )
    sandboxPolicy: SandboxPolicy | None = Field(
        None,
        description='Override the sandbox policy for this turn and subsequent turns.',
    )
    serviceTier: ServiceTier | None = Field(
        None,
        description='Override the service tier for this turn and subsequent turns.',
    )
    summary: ReasoningSummary | None = Field(
        None,
        description='Override the reasoning summary for this turn and subsequent turns.',
    )
    threadId: str
