# generated by datamodel-codegen:
#   filename:  v2/TurnCompletedNotification.json
#   timestamp: 2026-04-22T08:34:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description='A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.',
    )


class ByteRange(BaseModel):
    end: conint(ge=0)
    start: conint(ge=0)


class CodexErrorInfo(Enum):
    contextWindowExceeded = 'contextWindowExceeded'
    usageLimitExceeded = 'usageLimitExceeded'
    serverOverloaded = 'serverOverloaded'
    internalServerError = 'internalServerError'
    unauthorized = 'unauthorized'
    badRequest = 'badRequest'
    threadRollbackFailed = 'threadRollbackFailed'
    sandboxError = 'sandboxError'
    other = 'other'


class HttpConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo86(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    httpConnectionFailed: HttpConnectionFailed


class ResponseStreamConnectionFailed(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo87(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamConnectionFailed: ResponseStreamConnectionFailed


class ResponseStreamDisconnected(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo88(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseStreamDisconnected: ResponseStreamDisconnected


class ResponseTooManyFailedAttempts(BaseModel):
    httpStatusCode: conint(ge=0) | None = None


class CodexErrorInfo89(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    responseTooManyFailedAttempts: ResponseTooManyFailedAttempts


class CollabAgentStatus(Enum):
    pendingInit = 'pendingInit'
    running = 'running'
    interrupted = 'interrupted'
    completed = 'completed'
    errored = 'errored'
    shutdown = 'shutdown'
    notFound = 'notFound'


class CollabAgentTool(Enum):
    spawnAgent = 'spawnAgent'
    sendInput = 'sendInput'
    resumeAgent = 'resumeAgent'
    wait = 'wait'
    closeAgent = 'closeAgent'


class CollabAgentToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class Type(Enum):
    read = 'read'


class CommandAction(BaseModel):
    command: str
    name: str
    path: AbsolutePathBuf
    type: Type = Field(..., title='ReadCommandActionType')


class Type684(Enum):
    listFiles = 'listFiles'


class CommandAction77(BaseModel):
    command: str
    path: str | None = None
    type: Type684 = Field(..., title='ListFilesCommandActionType')


class Type685(Enum):
    search = 'search'


class CommandAction78(BaseModel):
    command: str
    path: str | None = None
    query: str | None = None
    type: Type685 = Field(..., title='SearchCommandActionType')


class Type686(Enum):
    unknown = 'unknown'


class CommandAction79(BaseModel):
    command: str
    type: Type686 = Field(..., title='UnknownCommandActionType')


class CommandAction75(
    RootModel[CommandAction | CommandAction77 | CommandAction78 | CommandAction79]
):
    root: CommandAction | CommandAction77 | CommandAction78 | CommandAction79


class CommandExecutionSource(Enum):
    agent = 'agent'
    userShell = 'userShell'
    unifiedExecStartup = 'unifiedExecStartup'
    unifiedExecInteraction = 'unifiedExecInteraction'


class CommandExecutionStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type687(Enum):
    inputText = 'inputText'


class DynamicToolCallOutputContentItem(BaseModel):
    text: str
    type: Type687 = Field(..., title='InputTextDynamicToolCallOutputContentItemType')


class Type688(Enum):
    inputImage = 'inputImage'


class DynamicToolCallOutputContentItem44(BaseModel):
    imageUrl: str
    type: Type688 = Field(..., title='InputImageDynamicToolCallOutputContentItemType')


class DynamicToolCallOutputContentItem42(
    RootModel[DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem44]
):
    root: DynamicToolCallOutputContentItem | DynamicToolCallOutputContentItem44


class DynamicToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class HookPromptFragment(BaseModel):
    hookRunId: str
    text: str


class McpToolCallError(BaseModel):
    message: str


class McpToolCallResult(BaseModel):
    field_meta: Any | None = Field(None, alias='_meta')
    content: list[Any]
    structuredContent: Any | None = None


class McpToolCallStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'


class MemoryCitationEntry(BaseModel):
    lineEnd: conint(ge=0)
    lineStart: conint(ge=0)
    note: str
    path: str


class MessagePhase(Enum):
    commentary = 'commentary'


class MessagePhase50(Enum):
    final_answer = 'final_answer'


class MessagePhase48(RootModel[MessagePhase | MessagePhase50]):
    root: MessagePhase | MessagePhase50 = Field(
        ...,
        description='Classifies an assistant message as interim commentary or final answer text.\n\nProviders do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.',
    )


class NonSteerableTurnKind(Enum):
    review = 'review'
    compact = 'compact'


class PatchApplyStatus(Enum):
    inProgress = 'inProgress'
    completed = 'completed'
    failed = 'failed'
    declined = 'declined'


class Type689(Enum):
    add = 'add'


class PatchChangeKind40(BaseModel):
    type: Type689 = Field(..., title='AddPatchChangeKindType')


class Type690(Enum):
    delete = 'delete'


class PatchChangeKind41(BaseModel):
    type: Type690 = Field(..., title='DeletePatchChangeKindType')


class Type691(Enum):
    update = 'update'


class PatchChangeKind42(BaseModel):
    move_path: str | None = None
    type: Type691 = Field(..., title='UpdatePatchChangeKindType')


class PatchChangeKind(
    RootModel[PatchChangeKind40 | PatchChangeKind41 | PatchChangeKind42]
):
    root: PatchChangeKind40 | PatchChangeKind41 | PatchChangeKind42


class ReasoningEffort(Enum):
    none = 'none'
    minimal = 'minimal'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'


class TextElement(BaseModel):
    byteRange: ByteRange = Field(
        ...,
        description='Byte range in the parent `text` buffer that this element occupies.',
    )
    placeholder: str | None = Field(
        None,
        description='Optional human-readable placeholder for the element, displayed in the UI.',
    )


class Type692(Enum):
    userMessage = 'userMessage'


class Type693(Enum):
    hookPrompt = 'hookPrompt'


class ThreadItem(BaseModel):
    fragments: list[HookPromptFragment]
    id: str
    type: Type693 = Field(..., title='HookPromptThreadItemType')


class Type694(Enum):
    agentMessage = 'agentMessage'


class Type695(Enum):
    plan = 'plan'


class ThreadItem223(BaseModel):
    id: str
    text: str
    type: Type695 = Field(..., title='PlanThreadItemType')


class Type696(Enum):
    reasoning = 'reasoning'


class ThreadItem224(BaseModel):
    content: list[str] | None = []
    id: str
    summary: list[str] | None = []
    type: Type696 = Field(..., title='ReasoningThreadItemType')


class Type697(Enum):
    commandExecution = 'commandExecution'


class ThreadItem225(BaseModel):
    aggregatedOutput: str | None = Field(
        None, description="The command's output, aggregated from stdout and stderr."
    )
    command: str = Field(..., description='The command to be executed.')
    commandActions: list[CommandAction75] = Field(
        ...,
        description='A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.',
    )
    cwd: AbsolutePathBuf = Field(..., description="The command's working directory.")
    durationMs: int | None = Field(
        None, description='The duration of the command execution in milliseconds.'
    )
    exitCode: int | None = Field(None, description="The command's exit code.")
    id: str
    processId: str | None = Field(
        None, description='Identifier for the underlying PTY process (when available).'
    )
    source: CommandExecutionSource | None = 'agent'
    status: CommandExecutionStatus
    type: Type697 = Field(..., title='CommandExecutionThreadItemType')


class Type698(Enum):
    fileChange = 'fileChange'


class Type699(Enum):
    mcpToolCall = 'mcpToolCall'


class ThreadItem227(BaseModel):
    arguments: Any
    durationMs: int | None = Field(
        None, description='The duration of the MCP tool call in milliseconds.'
    )
    error: McpToolCallError | None = None
    id: str
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Type699 = Field(..., title='McpToolCallThreadItemType')


class Type700(Enum):
    dynamicToolCall = 'dynamicToolCall'


class ThreadItem228(BaseModel):
    arguments: Any
    contentItems: list[DynamicToolCallOutputContentItem42] | None = None
    durationMs: int | None = Field(
        None, description='The duration of the dynamic tool call in milliseconds.'
    )
    id: str
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Type700 = Field(..., title='DynamicToolCallThreadItemType')


class Type701(Enum):
    collabAgentToolCall = 'collabAgentToolCall'


class Type702(Enum):
    webSearch = 'webSearch'


class Type703(Enum):
    imageView = 'imageView'


class ThreadItem231(BaseModel):
    id: str
    path: AbsolutePathBuf
    type: Type703 = Field(..., title='ImageViewThreadItemType')


class Type704(Enum):
    imageGeneration = 'imageGeneration'


class ThreadItem232(BaseModel):
    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: AbsolutePathBuf | None = None
    status: str
    type: Type704 = Field(..., title='ImageGenerationThreadItemType')


class Type705(Enum):
    enteredReviewMode = 'enteredReviewMode'


class ThreadItem233(BaseModel):
    id: str
    review: str
    type: Type705 = Field(..., title='EnteredReviewModeThreadItemType')


class Type706(Enum):
    exitedReviewMode = 'exitedReviewMode'


class ThreadItem234(BaseModel):
    id: str
    review: str
    type: Type706 = Field(..., title='ExitedReviewModeThreadItemType')


class Type707(Enum):
    contextCompaction = 'contextCompaction'


class ThreadItem235(BaseModel):
    id: str
    type: Type707 = Field(..., title='ContextCompactionThreadItemType')


class TurnStatus(Enum):
    completed = 'completed'
    interrupted = 'interrupted'
    failed = 'failed'
    inProgress = 'inProgress'


class Type708(Enum):
    text = 'text'


class UserInput71(BaseModel):
    text: str
    text_elements: list[TextElement] | None = Field(
        [],
        description='UI-defined spans within `text` used to render or persist special elements.',
        validate_default=True,
    )
    type: Type708 = Field(..., title='TextUserInputType')


class Type709(Enum):
    image = 'image'


class UserInput72(BaseModel):
    type: Type709 = Field(..., title='ImageUserInputType')
    url: str


class Type710(Enum):
    localImage = 'localImage'


class UserInput73(BaseModel):
    path: str
    type: Type710 = Field(..., title='LocalImageUserInputType')


class Type711(Enum):
    skill = 'skill'


class UserInput74(BaseModel):
    name: str
    path: str
    type: Type711 = Field(..., title='SkillUserInputType')


class Type712(Enum):
    mention = 'mention'


class UserInput75(BaseModel):
    name: str
    path: str
    type: Type712 = Field(..., title='MentionUserInputType')


class UserInput(
    RootModel[UserInput71 | UserInput72 | UserInput73 | UserInput74 | UserInput75]
):
    root: UserInput71 | UserInput72 | UserInput73 | UserInput74 | UserInput75


class Type713(Enum):
    search = 'search'


class WebSearchAction53(BaseModel):
    queries: list[str] | None = None
    query: str | None = None
    type: Type713 = Field(..., title='SearchWebSearchActionType')


class Type714(Enum):
    openPage = 'openPage'


class WebSearchAction54(BaseModel):
    type: Type714 = Field(..., title='OpenPageWebSearchActionType')
    url: str | None = None


class Type715(Enum):
    findInPage = 'findInPage'


class WebSearchAction55(BaseModel):
    pattern: str | None = None
    type: Type715 = Field(..., title='FindInPageWebSearchActionType')
    url: str | None = None


class Type716(Enum):
    other = 'other'


class WebSearchAction56(BaseModel):
    type: Type716 = Field(..., title='OtherWebSearchActionType')


class WebSearchAction(
    RootModel[
        WebSearchAction53 | WebSearchAction54 | WebSearchAction55 | WebSearchAction56
    ]
):
    root: WebSearchAction53 | WebSearchAction54 | WebSearchAction55 | WebSearchAction56


class ActiveTurnNotSteerable(BaseModel):
    turnKind: NonSteerableTurnKind


class CodexErrorInfo90(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTurnNotSteerable: ActiveTurnNotSteerable


class CodexErrorInfo84(
    RootModel[
        CodexErrorInfo
        | CodexErrorInfo86
        | CodexErrorInfo87
        | CodexErrorInfo88
        | CodexErrorInfo89
        | CodexErrorInfo90
    ]
):
    root: (
        CodexErrorInfo
        | CodexErrorInfo86
        | CodexErrorInfo87
        | CodexErrorInfo88
        | CodexErrorInfo89
        | CodexErrorInfo90
    ) = Field(
        ...,
        description='This translation layer make sure that we expose codex error code in camel case.\n\nWhen an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.',
    )


class CollabAgentState(BaseModel):
    message: str | None = None
    status: CollabAgentStatus


class FileUpdateChange(BaseModel):
    diff: str
    kind: PatchChangeKind
    path: str


class MemoryCitation(BaseModel):
    entries: list[MemoryCitationEntry]
    threadIds: list[str]


class ThreadItem220(BaseModel):
    content: list[UserInput]
    id: str
    type: Type692 = Field(..., title='UserMessageThreadItemType')


class ThreadItem222(BaseModel):
    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase48 | None = None
    text: str
    type: Type694 = Field(..., title='AgentMessageThreadItemType')


class ThreadItem226(BaseModel):
    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Type698 = Field(..., title='FileChangeThreadItemType')


class ThreadItem229(BaseModel):
    agentsStates: dict[str, CollabAgentState] = Field(
        ..., description='Last known status of the target agents, when available.'
    )
    id: str = Field(..., description='Unique identifier for this collab tool call.')
    model: str | None = Field(
        None, description='Model requested for the spawned agent, when applicable.'
    )
    prompt: str | None = Field(
        None,
        description='Prompt text sent as part of the collab tool call, when available.',
    )
    reasoningEffort: ReasoningEffort | None = Field(
        None,
        description='Reasoning effort requested for the spawned agent, when applicable.',
    )
    receiverThreadIds: list[str] = Field(
        ...,
        description='Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.',
    )
    senderThreadId: str = Field(
        ..., description='Thread ID of the agent issuing the collab request.'
    )
    status: CollabAgentToolCallStatus = Field(
        ..., description='Current status of the collab tool call.'
    )
    tool: CollabAgentTool = Field(
        ..., description='Name of the collab tool that was invoked.'
    )
    type: Type701 = Field(..., title='CollabAgentToolCallThreadItemType')


class ThreadItem230(BaseModel):
    action: WebSearchAction | None = None
    id: str
    query: str
    type: Type702 = Field(..., title='WebSearchThreadItemType')


class ThreadItem219(
    RootModel[
        ThreadItem220
        | ThreadItem
        | ThreadItem222
        | ThreadItem223
        | ThreadItem224
        | ThreadItem225
        | ThreadItem226
        | ThreadItem227
        | ThreadItem228
        | ThreadItem229
        | ThreadItem230
        | ThreadItem231
        | ThreadItem232
        | ThreadItem233
        | ThreadItem234
        | ThreadItem235
    ]
):
    root: (
        ThreadItem220
        | ThreadItem
        | ThreadItem222
        | ThreadItem223
        | ThreadItem224
        | ThreadItem225
        | ThreadItem226
        | ThreadItem227
        | ThreadItem228
        | ThreadItem229
        | ThreadItem230
        | ThreadItem231
        | ThreadItem232
        | ThreadItem233
        | ThreadItem234
        | ThreadItem235
    )


class TurnError(BaseModel):
    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo84 | None = None
    message: str


class Turn(BaseModel):
    completedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn completed.'
    )
    durationMs: int | None = Field(
        None,
        description='Duration between turn start and completion in milliseconds, if known.',
    )
    error: TurnError | None = Field(
        None, description="Only populated when the Turn's status is failed."
    )
    id: str
    items: list[ThreadItem219] = Field(
        ...,
        description='Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.',
    )
    startedAt: int | None = Field(
        None, description='Unix timestamp (in seconds) when the turn started.'
    )
    status: TurnStatus


class TurnCompletedNotification(BaseModel):
    threadId: str
    turn: Turn
